### ISSUE TITLE
about genotype and merged calls

### ISSUE THREAD

**Issue by nods-sparrow** [abyzovlab/CNVpytor#104]
Hi everyone.
Thank you for developing CNVpytor.  I used the program to call CNVs successfully, however, I cannot get any results after i use -genotype option after 50 minutes, just like this:
```
$cnvpytor -root DD1.pytor -conf AJ_genome_conf.py -genotype 1500
2022-03-16 08:31:05,185 - cnvpytor.genome - INFO - Reading configuration file 'AJ_genome_conf.py'.
2022-03-16 08:31:05,187 - cnvpytor.genome - INFO - Importing reference genome data: 'Ja'.
```
The other question is:
I have got the merged calls. Does the CN in bold stand for significant CNV? I noticed that some merged calls had same region but different significant cnvs. Why?
![1647394349(1)](https://user-images.githubusercontent.com/67611686/158499020-70e60a53-b06a-4eb0-8c07-0efbd6bf223e.png)

Many thanks

**Comment by suvakov** [comment]
Run with `-genotype` option CNVpytor expects an input: it reads regions from standard input (keyboard or redirected file) line by line. You can type regions, e.g. `chr01:1-10m` followed by `ENTER` or run with regions listed in a file (e.g. `regions.txt`):
```
$cnvpytor -root DD1.pytor -conf AJ_genome_conf.py -genotype 1500 < regions.txt
```
If you use keybord as input `CTRL+D` is way to exit (emulates end of file).

Answer to second question. CN in bold means that call is made in that sample and other samples are genotyped at that region. In this case looks all are significant (there is huge change in CN). However, e-values for individual samples you can get from individual calls. Another possibility is to use `-genotype` with `-a` option (see [example](https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#genotyping-genomic-regions)).

Thanks.

**Comment by nods-sparrow** [comment]
These are exactly what I want to know, thanks a lot.
