### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by jordimaggi** [abyzovlab/CNVpytor#105]
Hi,

I am trying to run cnvpytor as a python package following the Jupyter notebook example. I installed cnvpytor using conda.
The script fails right away during `import cnvpytor` with the following message:

``` 
File "/net/cephfs/home/jmaggi/.snakemake/scripts/tmp9h98zd6x.cnvpytor.py", line 5, in <module>
from PIL import Image
File "/data/jmaggi/condaenvs/snakemake/lib/python3.10/site-packages/PIL/Image.py", line 114, in <module>
from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/data/jmaggi/condaenvs/snakemake/lib/python3.10/site-packages/PIL/__init__.py)
```

I googled the issue and the only results I find relate to a package called `Pillow`, and most solutions in the discussion revolve around upgrade of the package. I tried to update everything using the `conda update --all` command, but all packages seem to be up-to-date.
Any suggestions?

**Comment by suvakov** [comment]
It looks that bug is related to `Pillow` installation. Maybe you should try different version of `Pillow` package.
