### ISSUE TITLE
update version on pypi & bioconda

### ISSUE THREAD

**Issue by ramprasadn** [abyzovlab/CNVpytor#106]
Hello!

CNVpytor version on bioconda&pypi is a bit dated. Would it be possible to update it to the latest version? 

Thanks!

**Comment by ramprasadn** [comment]
To add to this, I am using cnvpytor as a module in the nf-core project, and the module there is [stuck with version 1](https://github.com/nf-core/modules/blob/master/modules/cnvpytor/callcnvs/main.nf), because one of the project's requirements is that before a module can get updated in nf-core it should first be updated on bioconda, [and the current bioconda recipe for CNVpytor is dependent on whats available on PyPI](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/cnvpytor/meta.yaml). Due to these dependency issues between the different package managers, I am at a dead end right now unable to access the latest version (v1.2) in the nf-core project.

I am sure you have other pressing issues, so I just want to say that I would really appreciate it if you could only update the version on PyPi. Since its easy for anyone to submit a PR to bioconda, I can also take care of updating the recipe on bioconda myself. 

Cheers!

**Comment by arpanda** [comment]
Hi Ramprasad,
Thank you for the detailed description of your issue. I need to discuss the issue with other members first and I will let you know, once I have an update. 

Thanks
Arijit

**Comment by ramprasadn** [comment]
Hi Arijit,

Any updates yet? 😄 

Thanks,
Ram

**Comment by arpanda** [comment]
We are working on updating the pypi and bioconda repository. It will be available soon on bioconda.

**Comment by ramprasadn** [comment]
That's great! Thanks a lot, Arijit! 😄
