### ISSUE TITLE
Removing pathlib from the requirement

### ISSUE THREAD

**Issue by miyakokodama** [abyzovlab/CNVpytor#107]
Hi,

Said pathlib is now standard and no longer an external package, latest CNVpytor cannot be installed to anaconda. Would it be possible to remove pathlib from the requirement? 

I am having the same error as this person (https://github.com/abyzovlab/CNVpytor/issues/94) so am hoping to install the latest CNVpytor. 

Many thanks in advance!
Miyako

**Comment by arpanda** [comment]
Thank you for reporting the pathlib issue. I have updated the requirement setting to solve the issue of pathlib. 

For the #94, please let us know, if the latest version solve the issue or not. 

Thanks
Arijit

**Comment by miyakokodama** [comment]
Great, thanks for your quick reply! I will try out the newest version and let you know if I run into the same error. 

Thanks,
Miyako
