### ISSUE TITLE
 cnvpytor.viewer - WARNING - Missing reference genome required for gview.

### ISSUE THREAD

**Issue by ajkshdkjahdka** [abyzovlab/CNVpytor#11]
cnvpytor.viewer - WARNING - Missing reference genome required for gview.
what does that mean? i followed the steps, when i use plot:  cnvpytor.viewer - WARNING - Missing reference genome required for gview.
how can i fix it thank you so much

**Comment by suvakov** [comment]
What reference genome is used for alignment? It would help if you run:
`# cnvpytor -root yourfile.pytor -ls`
and paste output here?

**Comment by ajkshdkjahdka** [comment]
hi,sir,here is the results:
-bash-4.2$ cnvpytor -root file2.pytor -ls

Filename 'file2.pytor'
----------------------
File created: 2020-05-06 16:16 using CNVpytor ver 1.0b3

Chromosomes with RD signal: LG01, LG02, LG03, LG04, LG05, LG06, LG07, LG08, LG09                                                                                                             , LG10, LG11, LG12, LG13, LG14, LG15, LG16, LG17, LG18, LG19, LG20, LG21, LG22,                                                                                                              LG23, LG24, LG25, LG26, LG27

Chromosomes with SNP signal:

Reference genome is not set.

Chromosomes with RD histograms [bin sizes]:  []

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {'LG01': '361663492', 'LG02': '287913548', 'LG03': '20846181                                                                                                             0', 'LG04': '151666588', 'LG05': '140904605', 'LG06': '130473029', 'LG07': '1262                                                                                                             65066', 'LG08': '109091021', 'LG09': '103595202', 'LG10': '85359860', 'LG11': '7                                                                                                             7024298', 'LG12': '52098902', 'LG13': '49563362', 'LG14': '45746999', 'LG15': '4                                                                                                             5144064', 'LG16': '44486368', 'LG17': '36545738', 'LG18': '33603608', 'LG19': '2                                                                                                             6427661', 'LG20': '24972144', 'LG21': '24886238', 'LG22': '25008005', 'LG23': '2                                                                                                             3639164', 'LG24': '22227413', 'LG25': '21769585', 'LG26': '17122173', 'LG27': '1                                                                                                             0079314'}
-bash-4.2$


when i uesd -bash-4.2$ cnvpytor -root file.pytor -plot rd 100, the results showed like followed, how can i solve this problem?thank you

-bash-4.2$ cnvpytor -root file2.pytor -plot rd 100
2020-05-07 13:45:37,987 - cnvpytor.viewer - WARNING - Missing reference genome required for gview.
-bash-4.2$

**Comment by suvakov** [comment]
Hi,
Reference genome is missing for your data. CNVpytor package contains hg19 and hg38 human reference genomes. You can use it for other species but in that case you have to describe reference genome manually. Please find explanation is [here](https://github.com/abyzovlab/CNVpytor/blob/master/examples/AddReferenceGenome.md).
Briefly, make config file rg_conf.py containing:
```
import_reference_genomes = {
    "short_name": {
        "name": "full_nale",
        "species": "Name of species",
        "chromosomes": OrderedDict(
             [("LG01", (361663492,"A")), ("LG02", (287913548,"A")), 
             ....
        ]),
        "gc_file":"/..PATH../gc_file.pytor",
        "mask_file": "/..PATH../mask_file.pytor"
    }
}
```
File gc_file.pytor you can create from reference genome fasta:
```
cnvpytor -root MGSCv37_gc_file.pytor -gc ~/hg19/mouse.fasta.gz -make_gc_file
```
Mask file you can skip (by deleting that line in conf file).

Letter "A" next to chromosome length stands for autosome. What is ploidy of chromosomes in this case? Which species is it? CNVpytor was primarily developed for human genome but it should work for non-human genomes. If you have any suggestions you can contact me on mail (suvakov at gmail dot com). Thanks.
