### ISSUE TITLE
No sex chromosome calls using joint caller

### ISSUE THREAD

**Issue by maryawood** [abyzovlab/CNVpytor#110]
Hello, I noticed that when using the joint read depth/BAF caller, no CNV predictions are made on the sex chromosomes, even if the individual read depth and BAF callers predict events on them. (This is at least the case for hg38, which is the genome I've been working with.) Is this expected behavior?

**Comment by maryawood** [comment]
I wanted to follow up on the above to mention that the version in which I was seeing this behavior is v1.0. After working with the new version (v1.2.1), it appears that now the BAF only calling and joint calling both exclude sex chromosome calls from the results. It would be great to be able to detect events such as copy neutral LOH on chrX with CNVpytor.

**Comment by suvakov** [comment]
Unfortunately, we do not have it implemented yet. We are still developing those callers and plan is to include chrX in the case of female samples and PAR1/PAR2 in the case of male samples in future releases. 

There is a way to manually change type of chromosome from "S" to "A" using [config](https://github.com/abyzovlab/CNVpytor/blob/master/examples/AddReferenceGenome.md):

```
example_config.py
---
import_reference_genomes = {
    "hg38": {
            "name": "GRCh38",
            "species": "human",
            "chromosomes": OrderedDict(
                [("chr1", (248956422, "A")), ("chr2", (242193529, "A")), ("chr3", (198295559, "A")),
                 ("chr4", (190214555, "A")), ("chr5", (181538259, "A")), ("chr6", (170805979, "A")),
                 ("chr7", (159345973, "A")), ("chr8", (145138636, "A")), ("chr9", (138394717, "A")),
                 ("chr10", (133797422, "A")), ("chr11", (135086622, "A")), ("chr12", (133275309, "A")),
                 ("chr13", (114364328, "A")), ("chr14", (107043718, "A")), ("chr15", (101991189, "A")),
                 ("chr16", (90338345, "A")), ("chr17", (83257441, "A")), ("chr18", (80373285, "A")),
                 ("chr19", (58617616, "A")), ("chr20", (64444167, "A")), ("chr21", (46709983, "A")),
                 ("chr22", (50818468, "A")), ("chrX", (156040895, "A")), ("chrY", (57227415, "S")),
                 ("chrM", (16569, "M"))]),
            "gc_file": pkg_resources.resource_filename('cnvpytor', 'data') + "/gc_hg38.pytor",
            "mask_file": pkg_resources.resource_filename('cnvpytor', 'data') + "/mask_hg38.pytor",
            "ensembl_api_region": "https://rest.ensembl.org/overlap/region/human/{region}?content-type=application/json;feature=gene;"
        }
}
```

If you run CNVpytor using:
```
cnvpytor -conf example_config.py ...
```
it will assume chrX as diploid and should work fine in the case of female genome.

**Comment by maryawood** [comment]
I look forward to those updates, I think those will be great features! Thank you for the configuration suggestion in the meantime
