### ISSUE TITLE
Filtering based on distance from genome gaps (dG)

### ISSUE THREAD

**Issue by dr-ashu-geno** [abyzovlab/CNVpytor#116]
Dear developers,

Thank you so much for introducing CNVpytor.

Regarding the filtering step, I noticed that filtering CNVs based of distance from genome gaps, for example: set dG_range 100000 inf, excludes both deletions and duplications located less than 100kbp away from a genome gap, while there is no reason to exclude deletions located any distance from a genome gap. I asked a question in this regards in #115 too. 

I was wondering if you are considering modifying this behavior in next releases, 

Thank you,
Best,

**Comment by suvakov** [comment]
Thank you for useful suggestion. We will consider separating filters based on event type in future releases.

**Comment by xiucz** [comment]
@suvakov @arpanda 
Is there any plan to update the 'dG_range' parameter now? 
`view.dG_range = [1000, np.inf]`,  I filtered out most of the results using a 1000 bp cutoff.

https://github.com/abyzovlab/CNVpytor/issues/115#:~:text=What%20is%20the,understandable)%20not%20deletions.
