### ISSUE TITLE
Deletions at all chromosomes, location 1 

### ISSUE THREAD

**Issue by jon-coker** [abyzovlab/CNVpytor#12]
Thanks for the great tool! 

I have noted that cnvpytor calls deletions for all chr* at their beginnings (location 1).  This happens consistently when the bin size is 1000.   Most often, the size of the deletion is 10000.    As far as I know, these locations are filled with Ns and shouldn't have any reads at all.   

For example:

deletion	chr1:1-10000	10000	0.0000	0.000000e+00	0.000000e+00	0.000000e+00	0.000000e+00	-1.0000

A very similar call is found for all chromosomes in this 38 reference run.  The length is almost always 10000.  (I see one case for chr6 where the length is 1-60000).     

I am using [1000 10000 100000] for bin sizes.  With one exception, there are no such calls for 10000 or 100000 bin sizes.  The exception is 

 deletion	chr6:1-140000	140000	0.3122	1.128954e-02	1.241651e-48	1.128954e-02	1.241651e-48	0.9041

called with bin size 10000.  Again at chr6.  

It seems possible that there is a bug in the initial setup of the call iterations through a chromosome.   With the large spans of Ns I would think that 10000 bin sizes would also behave similarly, but, they do not seem to. 

There are other places that CNVs are called that are regions of long N's (but not, seemingly, all of them).  It may be that there is no connection between knowledge of Ns in the reference and CNVpytor calls.   

Jon

**Comment by suvakov** [comment]
Sorry for delay. As you suspected CNVpytor is making calls without knowledge of Ns. That is probably the reason for all false positive calls you refering. Inspired by your question we added additional column in caller output that provide percentage od Ns in CNV region. Using that value you can filter out such calls. New structure of columns is:

> CNV type: "deletion" or "duplication",
> CNV region (chr:start-end),
> CNV size,
> CNV level - read depth normalized to 1,
> e-val1 -- p value calculated using t-test statistics between RD statistics in the region and global,
> e-val2 -- p value from the probability of RD values within the region to be in the tails of a gaussian distribution of binned RD,
> e-val3 -- same as e-val1 but for the middle of CNV,
> e-val4 -- same as e-val2 but for the middle of CNV,
> q0 -- fraction of reads mapped with q0 quality in call region,
> pN -- fraction of reference genome gaps (Ns) in call region.

**Comment by jon-coker** [comment]
Dr. Suvakov,  thanks for the explanation, and the update.   Much appreciated.   J
