### ISSUE TITLE
Suggested filters for genotypes

### ISSUE THREAD

**Issue by Swanthana-bioinfo** [abyzovlab/CNVpytor#120]
Hello,

I see the following filters are suggested in issue #115 for genotypes. I am guessing these are filtered in .viewer step, correct me if I am wrong or Is there any way we use these filters during calling the genotypes? 

cnvpytor> set Q0_range -1 0.5        # filter calls with more than half not uniquely mapped reads
cnvpytor> set p_N 0 0.5              # filter calls with more than 50% Ns in reference genome 
cnvpytor> set size_range 300 inf     # filter calls smaller than 300bp (at least three bins)

Thank you.

**Comment by suvakov** [comment]
Yes, filtering is done in "viewer" step. It is not possible to do that in "call" step. 
It is possible to automatize this by piping script to viewer step after call step. This is an example bash script:
```
cnvpytor -root sample.pytor -rd sample.bam
cnvpytor -root sample.pytor -his 10000
cnvpytor -root sample.pytor -partition 10000
cnvpytor -root sample.pytor -call 10000
cnvpytor -root sample.pytor -view 10000 <<EOF > output_file.calls.tsv
set Q0_range -1 0.5
set p_N 0 0.5
set size_range 300 inf
print calls
EOF
```
