### ISSUE TITLE
snp plot

### ISSUE THREAD

**Issue by Azjer2014** [abyzovlab/CNVpytor#122]
Hello,
Thank you for this amazing tool that generates such amazing plots! I've noticed an issue with the snp plot. There are two ways to make the plots (1- interactive plotting mode 2-command line) and there are some discrepancies between them. I managed to make the snp and rd plots using the interactive plotting (panels rd snp). Now I'm trying to add the commands to a shell script but the only panels available for command line are ([rd] [likelihood] [baf]) despite what was written in the Wiki. If I try to call snp as a panel I get an error about it (see below). How can one generate the snp plot on the command line?

**The command in Wiki:**
 `cnvpytor -root file.pytor -plot [rd BIN_SIZE] [likelihood BIN_SIZE] [baf BIN_SIZE] [snp] [-o IMAGE_FILENAME]`
**My command:**
`cnvpytor -root file.pytor -plot regions 14:1-102M 500 -panels rd snp -style classic -rd_use_mask -o rd-snp_plot.png`
**The error**
cnvpytor: error: argument -panels/--panels: invalid choice: 'snp' (choose from 'rd', 'baf', 'likelihood')

**Comment by Azjer2014** [comment]
Hello,

Any update on how to resolve the error with the region plot and snp panel? I'd love to add these plots to my pipeline (one rd and snp image per chromosome) but the snp panel is not working in the region command.

Thanks!

**Comment by Azjer2014** [comment]
I generated the attacked plot using the interactive mode. How can I generate the same plot in the command line mode? 

<img width="538" alt="Plot" src="https://user-images.githubusercontent.com/109017995/180282843-1330a10b-4eae-429c-86e5-b20824116e83.png">

**Comment by Azjer2014** [comment]
I managed to solve this problem. I close this ticket.

**Comment by krukanna** [comment]
Hi, 
how did you manage to generate this plot from command line?

**Comment by Azjer2014** [comment]
They have a really good tutorial on the interactive mode. Once you wrote your settings in interactive mode then you can put your code in your pipeline using the following command: 
`cnvpytor -root YOUR-PYTOR-FILE -view 1000 <<ENDL
YOUR SETTINGS
THE CHROMOSOMES OF INTEREST
ENDL`
