### ISSUE TITLE
Empty TSV output (ref hg19)

### ISSUE THREAD

**Issue by manburst** [abyzovlab/CNVpytor#125]
Dear Sir
I tried to run cnvpytor to call CNV with Whole geneome sequence data aligned with hg19 (human genome)
there are no any errors pop up for each command but I get empty tsv output
I already type command `cnvpytor -download` to get data
Here my code
```
cnvpytor --root test.pytor -rd my_bam.sorted.bam -chrom chr 16

cnvpytor -root test.pytor -rg /Ref/hg19.fa

cnvpytor -root test.pytor -his 1000

cnvpytor -root test.pytor -partition 1000

cnvpytor -root test.pytor -call 1000 > calls.1000.tsv
```
I already tried with `cnvpytor -conf example_ref_genome_config.py -root test.pytor -rd my_bam.sorted.bam -chrom chr 16` from other issues report
but I got
`FileNotFoundError: [Errno 2] No such file or directory: 'example_ref_genome_config.py'`

Is anything I missed?
I am a newcomer to this field.

Thanks in advance

JK

**Comment by arpanda** [comment]
Hi,
CNVpytor already have stored hg19 reference genome data. So ignore `-rg` command. 

For the first command, I would suggest to ignore the `-chrom` parameter or use multiple chromosome names. So, you may use the following commands.
```
cnvpytor --root test.pytor -rd my_bam.sorted.bam 

cnvpytor -root test.pytor -his 1000

cnvpytor -root test.pytor -partition 1000

cnvpytor -root test.pytor -call 1000 > calls.1000.tsv
```

Thanks
Arijit

**Comment by manburst** [comment]
Thank you sir
It's worked!
but can you suggest how to plot rd plot specific chromosome on command line.
I always got plot of all chromosome
Here code I have tried
```
cnvpytor -root test.pytor -view 1000 -chrom 16
>cnvpytor rd
```
Thanks in advance
JK.

**Comment by manburst** [comment]
I already figured out myself
by 
```
cnvpytor -root test.pytor -view 1000
>cnvpytor chr16
```

Anyway, How to plot in higher resolution?
