### ISSUE TITLE
Plot with log scale, high cnv

### ISSUE THREAD

**Issue by jotanan98** [abyzovlab/CNVpytor#126]
Hi,
Is there any way i could generate a manhattan plot using log scaling on the y axis? I am working with cancer cell and have really high cnv on some chromosome. 

If its not possible, is there a way to output all the region that have more than 10X cnv? This way i could simply add a 'X' marker above the concerned chromosome.

Thank you for your time.

**Comment by suvakov** [comment]
Hi,
Sorry for delay. It is possible now (last commit). Two parameters should be set:
```
set rd_manhattan_log_scale
set rd_manhattan_range -5 5
manhattan
```
Units for range are based on Log2. Output should look like this (xkcd style):
![image](https://user-images.githubusercontent.com/23728854/185292699-f8fe9c4c-281c-4f09-becb-9b62b2ba4f8d.png)

Thanks

**Comment by jotanan98** [comment]
thanks!

**Comment by mtinti** [comment]
Hi, I was trying to get the plot in log scale as suggested, but my figure looks like this:
![image4](https://user-images.githubusercontent.com/8666061/192986554-9bedaabb-e2db-4772-bf07-c15d0d01043c.png)

any suggestion, please?
