### ISSUE TITLE
Failed to open the zip file downloaded

### ISSUE THREAD

**Issue by whzhangkui** [abyzovlab/CNVpytor#130]
I am sorry to tell you that, when I downloaded the zip from https://github.com/abyzovlab/CNVpytor, I cannot open it. Because it is said "Unpredictable end of compressed file“. The size of the zip file is 12943KB. The same thing has happened to the another github download from https://github.com/abyzovlab/CNVnator, which size is 14771KB. Please help me. Thank you!
[CNVpytor-master.zip](https://github.com/abyzovlab/CNVpytor/files/9391427/CNVpytor-master.zip)
[CNVnator-master.zip](https://github.com/abyzovlab/CNVpytor/files/9391431/CNVnator-master.zip)

**Comment by suvakov** [comment]
Size of the zip file should be around 130Mb usind `Download ZIP` button (see snapshot below):
 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/23728854/190936143-b66ccc6d-ae57-4ade-9bd8-65ec48b5e402.png">

Anyway, we suggest `git clone ...` instead  of downloading zip file.
