### ISSUE TITLE
cnvpytor.io - ERROR - Unable to open file test.pytor!

### ISSUE THREAD

**Issue by anubhabkhan** [abyzovlab/CNVpytor#139]
Hey,

I have been trying the execute the CNVpytor.ipynb. Initially it had run fine once. But after that, it keeps giving the error:

2022-09-21 16:23:35,462 - cnvpytor.io - ERROR - Unable to open file test.pytor! 

The command I tried to execute was: app = cnvpytor.Root("test.pytor", create=True, max_cores=24)

Could you please help?

Anubhab

**Comment by arpanda** [comment]
Hi,
The `app = cnvpytor.Root("test.pytor", create=True, max_cores=24)` code opens the pytor file in write mode. 
So, please make sure the `test.pytor` is not in use and you have write permission.

As you ran it once earlier, I think the file is still in use in the background. 

Thank You
Arijit

**Comment by anubhabkhan** [comment]
Oh okay. Thank you for the response. I will wait for the background jobs to get over then.
