### ISSUE TITLE
pileup command

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#14]
What does the pileup command do? Is it necessary? When should it be run exactly if so, and when relative to other commands like snp, baf, etc?

cnvpytor -root file.pytor -pileup file.bam

**Comment by suvakov** [comment]
It is explained [here](https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md) in paragraph _**Using SNP positions from variant file and counts from alignment file**_.

It is made to be used after -snp but before -mask_snps and -baf in the case when you do not have vcf for that particular sample but you have vcf based on other sample from the same person. Step -pileup will use positions of SNPs from vcf file and extract counts from bam file. In this case previous step (-snp) could be run with -noAD (it will not read counts).
