### ISSUE TITLE
VCF file format "not working for merged calls"

### ISSUE THREAD

**Issue by Talo07** [abyzovlab/CNVpytor#143]
Hi all,

Thank you for this good tool "CNVpytor"

I get the vcf file format only by sample but not on merged calls. Do you have any idea how I could get a vcf multisample ?

Thank you very much in advance,
Adham

**Comment by Talo07** [comment]
Hi, could someone have a vcf multisample from CNVpytor results ?

**Comment by Mrv0022** [comment]
Hi, could you solve your problem? I have the same issue. Can you explain how you did it?

thanks
