### ISSUE TITLE
CNV circular map

### ISSUE THREAD

**Issue by zainabae** [abyzovlab/CNVpytor#159]
Hello, is there any way to draw circular CNV map directly with Pytor files instead of using vcf files? 

![image](https://user-images.githubusercontent.com/42394514/211204993-8d531dac-faf7-4113-b9b9-64858d5e5053.png)

**Comment by suvakov** [comment]
Circular plots are generated directly from pythor file. However, circular plot depend on information about SNP BAF, so pythor file should contain information from VCF file previously imported. Using BAM/CRAM file is optional (see. alternative, green, path on pipeline figure: https://github.com/abyzovlab/CNVpytor#use-as-a-command-line-tool).
