### ISSUE TITLE
everything is empty !!

### ISSUE THREAD

**Issue by Indianhedgehog** [abyzovlab/CNVpytor#163]
Hi @suvakov @abyzov, I have a similar situation....everything is running fine, but the output calls are empty!
Also, the RD signal is empty! What could be the possible issue?

**Comment by arpanda** [comment]
Could you please check and share the output of `ls` commad. 
```
cnvpytor -root file.pytor -ls
```

-Arijit

**Comment by Indianhedgehog** [comment]
Hi Arijit,

here is the ls output
`
Filename 'test.pytor'
---------------------
File created: 2023-01-24 03:51 using CNVpytor ver 1.2.1

Chromosomes with RD signal:

Chromosomes with SNP signal:

Using reference genome: hg19 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]:  []

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {}`

**Comment by arpanda** [comment]
Your pytor file looks empty. How did you processed your data ?

**Comment by Indianhedgehog** [comment]
Hi @arpanda , i used the following command on my tumor bam file.

`cnvpytor --root test.pytor -rd sequencing/whole_genome_sequencing/view-by-pid/H021-3AT3LR/metastasis/paired/merged-alignment/metastasis_H021-3AT3LR_merged.mdup.bam -chrom chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY`

i am not sure what went wrong!

**Comment by arpanda** [comment]
did you run the `-his` and other steps ? if not please run the following steps. 
```
cnvpytor -root test.pytor -his 10000 100000
cnvpytor -root test.pytor -partition 10000 100000
cnvpytor -root test.pytor -call 10000 100000
```

Here I used two bin sizes and you may change those. Once you run the above commands and check the content using `ls` command.

**Comment by Indianhedgehog** [comment]
I did those steps earlier...output remains the same.

```
Filename 'test.pytor'
---------------------
File created: 2023-01-24 03:51 using CNVpytor ver 1.2.1

Chromosomes with RD signal:

Chromosomes with SNP signal:

Using reference genome: hg19 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]:  []

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {}
```

**Comment by arpanda** [comment]
Could you please check the chromosome names in the bam file. Are their names has `chr` or not. if not, please correct those names in `-chrom` input option or I would suggest you to remove the `-chrom` parameter from your rd step. It will read all the chromosomes from your bam input.

**Comment by Indianhedgehog** [comment]
I always forget how my chromosome names are formatted.
Had similar issues with other programs. 
It is running fine now !!!
Thanks for pointing it out, and for developing the awesome tool !!
