### ISSUE TITLE
which column is the copy number of the call result

### ISSUE THREAD

**Issue by 2236529177** [abyzovlab/CNVpytor#17]
![image](https://user-images.githubusercontent.com/25199946/89704015-00778f00-d983-11ea-87d3-756084376e62.png)
which column is the copy number of the call result. thanks a lot

**Comment by suvakov** [comment]
CNV level column represents CN normalized to 1 as normal level. It means that for male X and Y chromosomes CNV level is the same as copy number, while for autosomes copy number is 2 * CNV level.
