### ISSUE TITLE
Invalid VCF produced by `cnvpytor view`

### ISSUE THREAD

**Issue by archmageirvine** [abyzovlab/CNVpytor#178]
When I do
```
cnvpytor -root file.pytor -view 1000
set print_filename output.vcf
print calls
```

The resulting VCF  is invalid in at least three ways:

1. The header line for `GT` contains a trailing `;` that should not be there:

```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">;
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Copy number genotype for imprecise events">
```

2. The REF column is all missing `.`, but that is not permitted in VCF v4.1 (use `N` instead).

3. The `CN` FORMAT field is defined to be Integer, but some records are coming out with floating-point values in that field:

```
1       145097001       CNVpytor_dup79  .       <DUP>   .       PASS    END=145326000;IMPRECISE;SVLEN=229000;SVTYPE=DUP;pytorRD=2.514962864006279;pytorP1=0.0;pytorP2=0.0;pytorP3=0.0;pytorP4=0.0;pytorQ0=0.1908020972780009;pytorPN=0.0;pytorDG=286400.0;pytorCL=rd_mean_shift GT:CN   ./1:2.51
```

All of these I can manually work around by correcting the problems with `sed` etc., but it would be nice to have these fixed in the tool itself.

**Comment by arpanda** [comment]
We fixed both the 1 and 3 point previously. This is the current vcf header for GT and CN tag.
```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=CN,Number=1,Type=Float,Description="Copy number genotype for imprecise events">
```

> The REF column is all missing ., but that is not permitted in VCF v4.1 (use N instead).

Thanks for pointing this out. I updated the ref column to `N` 

-Arijit
