### ISSUE TITLE
How to download reference genome resource files manually?

### ISSUE THREAD

**Issue by xiekunwhy** [abyzovlab/CNVpytor#180]
Hi,

Is there a way to download reference genome resource files manually, instead of using cnvpytor -download? Because I always connect failed.

Best,
Kun

**Comment by suvakov** [comment]
Yes, you can download them manually from:
[https://github.com/abyzovlab/CNVpytor/tree/master/cnvpytor/data](https://github.com/abyzovlab/CNVpytor/tree/master/cnvpytor/data)
and store them to the installation destination ```[PATH]/cnvpytor/data/``` folder.

**Comment by suvakov** [comment]
However, better way is to install cnvpytor directly from github:
```
pip install git+https://github.com/abyzovlab/CNVpytor.git
```

**Comment by xiekunwhy** [comment]
Thank you for your reply, I will pip install git+https://github.com/abyzovlab/CNVpytor.git.
