### ISSUE TITLE
error in viewer.print_calls_file

### ISSUE THREAD

**Issue by briankegerreis** [abyzovlab/CNVpytor#185]
When trying to plot calls following the joint caller example, I get the following error: `NameError: name 'c' is not defined`

Line 1191 of viewer.py references `c`, which does not exist. I assume it should refer to a chromosome

https://github.com/abyzovlab/CNVpytor/blob/5d573f2c38f583aac0b20102d655ef05d64a81c2/cnvpytor/viewer.py#L1185-L1191

**Comment by arpanda** [comment]
Thank you for the report. Could you please share the command you used? This information will help me to reproduce and fix the bug.

-Arijit

**Comment by arpanda** [comment]
I have fixed the bug. Thank you for the report.
