### ISSUE TITLE
multiple normal libraries as input

### ISSUE THREAD

**Issue by lmanchon** [abyzovlab/CNVpytor#186]
--Hi,

is CNVpytor can be used with a PON (panel of normal libraries) to compare with a single tumor librarie ?

thank you --

**Comment by arpanda** [comment]
Hi,
Can you provide more details about your query? Specifically, what type of comparison are you looking to make using the PON?

Thank you,
Arijit

**Comment by lmanchon** [comment]
--Hi,

i try to find CNV on a tumor library and i have 11 normal libraries to make a PON as it usual to do (like PureCN ,CNVKit or GATK CNV caller requirements).
Is CNVpytor use only 2 librairies (tumor vs normal), or is it possible to specify a PON as parameter ?

thank you --

**Comment by arpanda** [comment]
To clarify, your goal is to identify and exclude the Copy Number Variations (CNVs) that have already been detected in your normal sample/s. This can be achieved through few approaches.

One approach is to process individual samples and then look for the CNV calls in the tumor compared to normal. Please have a look at this example: https://github.com/abyzovlab/CNVpytor/blob/master/examples/merging.md, if it helps.


Thank you
Arijit

**Comment by arpanda** [comment]
Great.
For exome data, you can use the vcf input to call CNV. Please have a look at the `snp2rd` command and follow the steps, it utilizes variant's read depth information. I would suggest to use a very high bin size for this purpose. Maybe 100 000, 500000 or 1000000.

**Comment by lmanchon** [comment]
i have only bam files and corresponding vcf files computed by Mutect2.
isn't it risky to use big bins? --> Small CNVs may not be detected

**Comment by arpanda** [comment]
I would recommend using germline variants for the variants input. You have targeted exome right? its depends on the proportion genomic regions it coverts.

**Comment by lmanchon** [comment]
how to have germline variants ?
% proportion covered: 32800 probes of 300 base pairs spread across the genome (hg38)
