### ISSUE TITLE
pytorDG=0 for everything when using pytorCL=combined_mosaic

### ISSUE THREAD

**Issue by trjojack** [abyzovlab/CNVpytor#189]
When using the combined caller (combined_mosaic), all entries in the vcf file have pytorDG=0 which prevents filtering out calls close to gaps in the ref genome, as for the rd_mean_shift caller.

**Comment by arpanda** [comment]
Currently, the combined caller (combined_mosaic) output doesn't have DG value, it has pNS [fraction of reference genome gaps (Ns) within call segments]. Please have a look at this description.

![](https://raw.githubusercontent.com/abyzovlab/CNVpytor/master/imgs/joint_caller_output.png)

The VCF input doesn't report the pNS value, I will update the vcf output to include the pNS field.

Thank you,
Arijit
