### ISSUE TITLE
Eval1

### ISSUE THREAD

**Issue by zainabae** [abyzovlab/CNVpytor#192]
Hello, 
I am curious to know if using the -chrom option in cnvpytor will cause the eval1 output to be the result of multiplying the p-value with the size of the autosomes divided by the bin size, or if it will use the whole genome size instead.

**Comment by arpanda** [comment]
During `RD` step, if too few chromosomes are provided, it will impact the global statistics.

**Comment by zainabae** [comment]
> During `RD` step, if too few chromosomes are provided, it will impact the global statistics. 

I'm selecting 36 autosome 
 In this case: 

the eval = autosomes size * p- value / bin size 

Or eval1 = whole genome size * p-value /bin size ?

**Comment by suvakov** [comment]
We always assume the human genome in this formula, with `genome_size=2.9e9`. When using `cnvpytor` from Python, you can adjust the genome size by specifying it as an argument: `Root.call(..., genome_size=2.9e9)`. Alternatively, you can adjust that column manually. Thanks for pointing this out. In the future, we should determine this based on the reference genome size.

**Comment by zainabae** [comment]
> We always assume the human genome in this formula, with `genome_size=2.9e9`. When using `cnvpytor` from Python, you can adjust the genome size by specifying it as an argument: `Root.call(..., genome_size=2.9e9)`. Alternatively, you can adjust that column manually. Thanks for pointing this out. In the future, we should determine this based on the reference genome size.


Thank you for the quick and informative response 👍🏻
And this is applied even when using non-human organism?

**Comment by suvakov** [comment]
Yes, it is hard coded in current version.
