### ISSUE TITLE
call output is empty

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#2]
Hi,
CNVpytor seems to run fine with no errors. However, when I run the -call function, all the outputs are empty files.

Below is the -ls output. What is the issue?

Filename 'file.pytor'
---------------------
File created: 2020-03-10 02:13 using CNVpytor ver 1.0

Chromosomes with RD signal: chr22

Chromosomes with SNP signal: 

Using reference genome: hg38 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]: chr22 [1000, 10000, 100000]

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {'chr22': '50818468'}

**Comment by suvakov** [comment]
Maybe there are no calls (chr22 is not so long).
What command line you used for calls?

**Comment by gevro** [comment]
Can't be, because regular CNVnator had many calls on chr22.
I tried:
cnvpytor -root file.pytor -call 100 > output
cnvpytor -root file.pytor -call 1000 > output
cnvpytor -root file.pytor -call 10000 > output

I also tried cnvpytor -root file.pytor -call 100 1000 10000
, as described in your documentation, but this kind of calling isn't clear what the output would be anyway.

I can privately share with you the ROOT file if you want on dropbox.

**Comment by suvakov** [comment]
Ok. My email is suvakov at gmail. Thanks

**Comment by suvakov** [comment]
This bug is fixed. Thanks.

**Comment by Indianhedgehog** [comment]
Hi @suvakov @abyzov , I have a similar situation....everything is running fine, but the output calls are empty!
