### ISSUE TITLE
confidence scores for forced genotyping outputs

### ISSUE THREAD

**Issue by mgonzalezporta** [abyzovlab/CNVpytor#20]
Our team is using CNvpytor as part of a multi-step workflow to identify CNVs in a large cohort of samples (WGS, n=10K). The workflow steps are as follows:

1. Run CNVpytor on a single-sample basis to discover CNV candidates (`his` + `partition` + `call` commands).
2. Cluster CNV candidates across all samples using svtk bedcluster.
3. Force-genotype the final list of clustered candidates in each sample using CNVpytor (`genotype` command).

Whilst we get various statistics that allow us to filter the outputs of step 1 (e-vals, q0...), the last step is only issuing a predicted CN state. Is there any way to extend the outputs of the genotyping module to also include confidence scores for its genotype predictions?

Thanks,

**Comment by suvakov** [comment]
We are extending genotype command. With -a option it will print out following columns:

1. region;
2. cnv level: mean RD normalized to mean autosomal RD level;
3. e_val_2: p value from the probability of RD values within the region to be in the tails of a gaussian distribution of binned RD;
4. q0 – fraction of reads mapped with q0 quality within call region;
5. pN – fraction of reference genome gaps (Ns) within call region; 
6. Number of homozygous variants within region; 
7. Number of heterozygous variants; 
8. BAF level estimated using maximum likelihood method; 
9. p-value based on BAF signal.

Columns 6-9 require -snp and -baf step to be executed before with same bin size.

It is in developing phase. Please let us know if you have suggestion what other values could be useful to print out.

Thanks

**Comment by mgonzalezporta** [comment]
Many thanks, that would certainly be very useful.

As for additional columns, it may be worth adding `e_val_1` (and even `e_val_3` and `e_val_4`) to align with the outputs of the `call` command.

**Comment by suvakov** [comment]
We added e_val1 to output:
1. region;
2. cnv level: mean RD normalized to mean autosomal RD level;
3. e_val_1:
4. e_val_2: p value from the probability of RD values within the region to be in the tails of a gaussian distribution of binned RD;
5. q0 – fraction of reads mapped with q0 quality within call region;
6. pN – fraction of reference genome gaps (Ns) within call region;
7. Number of homozygous variants within region;
8. Number of heterozygous variants;
9. BAF level estimated using maximum likelihood method;
10. p-value based on BAF signal.
