### ISSUE TITLE
Region plot: No data for likelihood. Try with lh_lite parameter.

### ISSUE THREAD

**Issue by evayfang2019** [abyzovlab/CNVpytor#201]
According to the example ([region.md](https://github.com/abyzovlab/CNVpytor/blob/master/examples/region.md)), it reported “No data for likelihood. Try with lh_lite parameter”, as shown in the following figure.

*.aligned.sort.bam: alignment by minimap2 and sorting by samtools
*.vcf.gz: snp calling by deepvariant

```
### Region plot example
# sample1
cnvpytor -root kid.pytor -rd kid.aligned.sort.bam
cnvpytor -root kid.pytor -his 100000
cnvpytor -root kid.pytor -snp kid.minimap2.dpv.vcf.gz
cnvpytor -root kid.pytor -mask_snps
cnvpytor -root kid.pytor -baf 100000

# sample2
cnvpytor -root ma.pytor -rd ma.aligned.sort.bam
cnvpytor -root ma.pytor -his 100000
cnvpytor -root ma.pytor -snp ma.minimap2.dpv.vcf.gz
cnvpytor -root ma.pytor -mask_snps
cnvpytor -root ma.pytor -baf 100000

# sample3
cnvpytor -root pa.pytor -rd pa.aligned.sort.bam
cnvpytor -root pa.pytor -his 100000
cnvpytor -root pa.pytor -snp pa.minimap2.dpv.vcf.gz
cnvpytor -root pa.pytor -mask_snps
cnvpytor -root pa.pytor -baf 100000

# interactive plotting mode with all sample
cnvpytor -root  kid.pytor ma.pytor pa.pytor -view 100000
cnvpytor> set style classic
cnvpytor> set rd_use_mask
cnvpytor> set file_titles kid ma pa
cnvpytor> set panels rd likelihood snp
cnvpytor> set markersize 0.2
cnvpytor> 17:80M-85M
cnvpytor> save image.png
cnvpytor> quit
```

![image](https://github.com/abyzovlab/CNVpytor/assets/75374188/e2569b9d-e188-4c64-a3a5-d1e322479320)

**Comment by arpanda** [comment]
For the region plot, precise chromosome names are required. We expect to address this in a future update.

The read depth panel appears to be empty, possibly because of chromosome names. Please verify the presence of the 'chr' prefix in the chromosome names using the `ls` command. If the 'chr' prefix is present, please attempt it with 'chr17:80M-85M.'


Thank you,
Arijit

**Comment by evayfang2019** [comment]
It works when adding "chr". Thank you!
