### ISSUE TITLE
haploid genome error

### ISSUE THREAD

**Issue by cfz1998** [abyzovlab/CNVpytor#204]
All chromosome types were specified as "S" for my reference genome.

![image](https://github.com/abyzovlab/CNVpytor/assets/60096719/67e4fec5-2596-47a3-9ab7-a6efa54771e7)

I still got Heterozygote. What's the problem?

![image](https://github.com/abyzovlab/CNVpytor/assets/60096719/1f44f2cd-ec20-4ff5-ba2d-ccf5e8eebe1f)

**Comment by arpanda** [comment]
Many cnvpytor functions are hardcoded assuming the gnome is diploid. The VCF output is one of those functions. It appears that the snapshot in question is derived from the VCF output of the call.

Please manually inspect the Manhattan plot and calls if its make sense or not to proceed for the analysis.  

-Arijit
