### ISSUE TITLE
CNVpytor Parameters

### ISSUE THREAD

**Issue by zainabae** [abyzovlab/CNVpytor#206]
Hello,

I have a question about the default parameter selection.

In my thesis project, I employed default parameters for CNV filtering. However, the reviewer has requested an explanation for the bioinformatic significance behind choosing these defaults in the software, specifically pN > 50%, q0 > 50%, and excluding CNVs smaller than the size of 3 bins. I am uncertain about why the default threshold is set at these values? Is this based on specific equation or sensitivity analysis?

**Comment by arpanda** [comment]
Here is the description for q0 and pN: 

- q0: The proportion of reads mapped with q0 quality in call segments, serving as an indicator of the overall mapping quality of the reads. 
- pN: The proportion of gaps (Ns) in the reference genome within the call region, aiding in the identification of gaps in the genome. 

The purpose of utilizing pN and q0 is to eliminate regions in the genome that are characterized by low confidence and noise, such as those with gaps or low mapping quality.

The number of bins in a call also helps to reduce the noises/false positive calls that can arise for many reasons like repeat regions, complex sequence structure etc. The threshold increases the confidence for the call. The number is based on basic intuition. 

I'm unsure if this addresses your question adequately.

-Arijit
