### ISSUE TITLE
Bin size

### ISSUE THREAD

**Issue by zainabae** [abyzovlab/CNVpytor#212]
Hello, I'm planning to analyze two groups of samples from the same species for a single study. One group was sequenced at a depth of 10x coverage, while the other group ranges from 20 to 30x coverage. 
When selecting a bin size for all samples, would it be suitable to choose 500, even for the 10x samples? My goal is to merge them into a single population for analysis.

**Comment by arpanda** [comment]
I should be fine with a bin size of 500 for 10x coverage sample. 

-Arijit
