### ISSUE TITLE
How to interpret merged_calls result from command line

### ISSUE THREAD

**Issue by NannapatS** [abyzovlab/CNVpytor#214]
Hi
I used command line on HPC as below for trio sample.
cnvpytor -root  proban1.pytor  father1.pytor mother1.pytor -view 100000
set Q0_range -1 0.5        
set p_range 0 0.0001       
set p_N 0 0.5            
set size_range 50000 inf   
set dG_range 100000 inf    
set print_filename mergedtrio1view100000annotatemerge.tsv 
set annotate         
print merged_calls              
quit

Then I got result as below
![Capture](https://github.com/abyzovlab/CNVpytor/assets/47264060/8ec1eba1-5e5b-4dfb-8236-78978b1798cb)

My question are
1. I think data on column D, E and F that are copy number, doesn't I.
2. What does the values on column G?
Please help me, thank a lot anyone in advance.

**Comment by arpanda** [comment]
You are correct. The columns D, E, and F correspond to the copy number of your samples, while column G indicates the index of the sample where CNV is called. 

In Row 2, a CNV call is identified for samples 1 and 2, but not for sample 0. In Row 3, the region's coordinates differ from those in Row 2, and it is identified as a CNV solely in sample 0.

- Arijit
