### ISSUE TITLE
Location example_ref_genome_conf.py in anaconda

### ISSUE THREAD

**Issue by RenscoHogers** [abyzovlab/CNVpytor#215]
Hi,

I am currently using CNVpytor using an anaconda container, however I cannot find example_ref_genome_conf.py which I need to use my reference genome.

Do you have any clue about where I can find this script in the container?

**Comment by arpanda** [comment]
Your query is not clear to me. Could you please elaborate a bit. 

If you are taking about [Configuring reference genome](https://github.com/abyzovlab/CNVpytor/blob/master/examples/AddReferenceGenome.md).  The `example_ref_genome_conf.py` is for the user to create to load custom reference genome. We have only limited number of pre-configured reference genomes. 

-Arijit

**Comment by RenscoHogers** [comment]
In your tutorial "AddReferenceGenome.md" you include the following line:
To use CNVpytor with new reference genome us -conf option in each cnvpytor command, e.g.
`cnvpytor -conf REL_PATH/example_ref_genome_conf.py -root file.pytor -rd file.bam`

I would like to know where I can find the "example_ref_genome_conf.py" script so I can link it.
I am using the anaconda container (https://anaconda.org/bioconda/cnvpytor). Not sure if that makes any difference.

**Comment by arpanda** [comment]
There is no such file with cnvpytor package. The `example_ref_genome_conf.py` is for the user to create.
