### ISSUE TITLE
Could you tell us how to use "plot" option?

### ISSUE THREAD

**Issue by tak-nagano** [abyzovlab/CNVpytor#22]
Hi,
We tried to do any "plot" command, but it shows an error response as shown below every time.

[ERROR]
```
Traceback (most recent call last):
  File "/usr/local/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/cnvpytor/__main__.py", line 226, in main
    view.plot(args.plot)
TypeError: 'bool' object is not callable
```

[Our command]
cnvpytor -conf ../xxx.py -root file.pytor -plot regions VIII:465501-465900 100 -panels rd -o test_region

We are not sure the detail in code, but are wondering that L337 in viewer.py has some trouble.
Could you tell us how to fix or use this "plot" command the detail more than your instruction?

[Environment]
Our python version is "python2.7.17"

p.s.
Also as you seen above, we'd like to add our command to "--conf" option, because..
We followed the tutorial ( https://github.com/abyzovlab/CNVpytor/blob/master/examples/AddReferenceGenome.md ) to create the original config.
We don’t have strict mask in the same format as 100 Genomes Project strict mask, so, we don’t write about a mask file in the config.
Does the config affect this trouble?

Thank you as advance.

**Comment by suvakov** [comment]
We had a bag. Thank you for letting us know. It should work now.

However, our suggestion is to use interactive mode for plotting (-view bin_size). This way you will have access to more parameters (type 'show' or 'help'). We started with both possibilities but in future we will develop only interactive mode. If you want to automatize plotting you can store commands in file and redirect them to cnvpytor:
```
# cnvpytor -root file.pytor -view 100 < script_file
```
or
```
# cnvpytor -root file.pytor -view 100 <<END
set output_filename file.png
VIII:465501-465900
END
```
In few weeks we will update documentation with more examples. 

Thanks.

**Comment by tak-nagano** [comment]
Thanks suvakov.
We tried to do as well above, but got an error shown below.
```
TclError: no display name and no $DISPLAY environment variable
```

Our environment consists linux server which has no GUI.
Could you tell us another way or please fix your code?

**Comment by suvakov** [comment]
Sorry for delay. Please try to run cnvpytor with -agg (or --force_agg option). Thanks

**Comment by tak-nagano** [comment]
thnaks, @suvakov .
We check the command as you suggested.
