### ISSUE TITLE
likelihood picture drawing problem

### ISSUE THREAD

**Issue by LHlearningcode** [abyzovlab/CNVpytor#220]
Hi there, I am a beginner in cnvpytor software ，and I have a problem with drawing likelihood images.
My likelihood signal is not very obvious, which may be due to the sequencing depth and sequencing library preparation method. Anyway, I want to modify the background of the image or something to make my image more contrasty and easier to reflect the content of the image. I tried some panels, but the effect is still not good. Is there any way to customize the color of the image? Thank you very much, this is very important to me.
huan liu
![output regions 0001](https://github.com/abyzovlab/CNVpytor/assets/93306358/1b7e9b46-1772-4097-882d-dca37ab8f3c1)

**Comment by arpanda** [comment]
Currently, there is no direct option in `CNVpytor` to update the background of this image. 

The plotting is done using matplotlib's `imshow`, which uses the default colormap (`cmap`). However, it is possible to update the default colormap. I have created an example in Google Colab to demonstrate this, which you can view at [this link](https://colab.research.google.com/drive/1QFQoz-r7cH7XG4EOHAgjBe9iA3IWVqFQ?usp=sharing).

Thanks
Arijit

**Comment by LHlearningcode** [comment]
Wow, that's GREAT!!! Thanks a lot!! You are my hero,hahaha!
Love from China!
