### ISSUE TITLE
mask region

### ISSUE THREAD

**Issue by Xscut** [abyzovlab/CNVpytor#229]
When I use -call with -rd_use_mask, 
the masked region will be called as a deletion. 
How can I prevent the masked region from being called in the results

**Comment by suvakov** [comment]
Which caller you are using and what bin size?

**Comment by Xscut** [comment]
> Which caller you are using and what bin size?

the command being used is `cnvpytor -root xxx.pytor -call 1000 -rd_use_mask`

**Comment by suvakov** [comment]
Use -filter_nan in both the -partition and -call steps:
```
cnvpytor -root xxx.pytor -partition 1000 -rd_use_mask -filter_nan
cnvpytor -root xxx.pytor -call 1000 -rd_use_mask -filter_nan
```
However, this is a new feature, so update CNVpytor from the GitHub source:
```
pip uninstall -y cnvpytor && pip install git+https://github.com/abyzovlab/CNVpytor.git
```
We would appreciate feedback from you on whether this solves the problem. Thank you for raising this question.

**Comment by Xscut** [comment]
> Use -filter_nan in both the -partition and -call steps:
> 
> ```
> cnvpytor -root xxx.pytor -partition 1000 -rd_use_mask -filter_nan
> cnvpytor -root xxx.pytor -call 1000 -rd_use_mask -filter_nan
> ```
> 
> However, this is a new feature, so update CNVpytor from the GitHub source:
> 
> ```
> pip uninstall -y cnvpytor && pip install git+https://github.com/abyzovlab/CNVpytor.git
> ```
> 
> We would appreciate feedback from you on whether this solves the problem. Thank you for raising this question.

Thank you very much; this problem has been solved successfully.
