### ISSUE TITLE
Nothing output from cnvpytor -call

### ISSUE THREAD

**Issue by ld9866** [abyzovlab/CNVpytor#238]
Dear developer:

I am trying to detect CNV, but I noticed that I did not generate any result files in several test individuals, I would like to ask what is the reason?

The species that we're using are agricultural animals and I think that's not the fundamental problem, what's going on

I have uploaded my code and the result file, please help me have a look.

Best Day

Dong

The code:

cnvpytor -root SRR9599724.pytor -rd SRR9599724.bam -chrom 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18  X Y MT 
cnvpytor -root SRR9599724.pytor -his 10000 100000
cnvpytor -root SRR9599724.pytor -partition 10000 100000
cnvpytor -root SRR9599724.pytor -call 10000 > SRR9599724.10000.tsv
cnvpytor -root SRR9599724.pytor -call 100000 > SRR9599724.100000.tsv

[SRR9599724.zip](https://github.com/user-attachments/files/16827121/SRR9599724.zip)
000 > SRR9599724.100000.tsv

**Comment by arpanda** [comment]
CNVpytor comes with limited number of reference genomes (mostly human i.e., hg19, hg38 etc) and users can create their reference genome. I believe, you are missing the reference genome setup step. 
Steps to setup a custom reference genome: https://github.com/abyzovlab/CNVpytor/blob/master/examples/AddReferenceGenome.md

Once you create your reference genome config, there is no need to run the `rd` step. Just start from setting up the reference genome and re-run other steps. 

 -Arijit

**Comment by ld9866** [comment]
Dear developer:

l create the reference configure with "cnvpytor -root Pig_gc_file.pytor -gc Pig.fa -make_gc_file" which works ok. and l prepared the pig_ref_genome_conf.py and run the "cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root ERS804988.pytor -rd ERS804988.bam -chrom 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18  X Y MT"

The printsreen showed that "2024-09-01 11:43:33,650 - cnvpytor.utils - WARNING - Problem with fit: negative mean. Using mean and std instead fitting parameters!"

And l still cannot work properly!

Best 
Dong

[pig_ref_genome_conf.zip](https://github.com/user-attachments/files/16827258/pig_ref_genome_conf.zip)

**Comment by arpanda** [comment]
could you please try running the 'rd' step without `chrom` parameter and run with `-v d` parameter to get detailed log.
```
cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root ERS804988.pytor -rd ERS804988.bam
```
then the other steps:
```
cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root ERS804988.pytor -his 10000 100000

cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root ERS804988.pytor -partition 10000 100000

cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root SRR9599724.pytor -call 10000 > SRR9599724.10000.tsv
```

Also, please check the Manhattan plot and it will show how the read depth looks. 
-Arijit

**Comment by ld9866** [comment]
Dear developer:

I tried according to your prompt, but still did not get the result file. I used "script ERS804988.log" to record the events that appeared on the screen. Could you please help me find out why?

Best Day

Dong

cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root ERS804988.pytor -rd ERS804988.bam
cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root ERS804988.pytor -his 10000 100000
cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root ERS804988.pytor -partition 10000 100000
cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root ERS804988.pytor -call 10000 > ERS804988.10000.tsv

[ERS804988.log](https://github.com/user-attachments/files/16827319/ERS804988.log)

**Comment by arpanda** [comment]
I checked the log. It seems, the coverage is too low and because of this global depth calculation is not working properly. Here are some of the logs:

```
2024-09-01 12:31:04,323 - cnvpytor.root - INFO - GC content for reference genome 'pig11' found in database.
2024-09-01 12:31:04,534 - cnvpytor.root - INFO - Chromosome '10' stat - RD parity distribution gaussian fit:  5.80 +- 3.12
2024-09-01 12:31:04,560 - cnvpytor.root - INFO - Chromosome '11' stat - RD parity distribution gaussian fit:  6.03 +- 3.17
2024-09-01 12:31:04,580 - cnvpytor.root - INFO - Chromosome '12' stat - RD parity distribution gaussian fit:  4.71 +- 3.36
2024-09-01 12:31:04,644 - cnvpytor.root - INFO - Chromosome '13' stat - RD parity distribution gaussian fit:  6.32 +- 3.12
2024-09-01 12:31:04,884 - cnvpytor.root - INFO - Chromosome '1' stat - RD parity distribution gaussian fit:  6.30 +- 3.13
2024-09-01 12:31:04,932 - cnvpytor.root - INFO - Chromosome '2' stat - RD parity distribution gaussian fit:  5.87 +- 3.29
2024-09-01 12:31:04,974 - cnvpytor.root - INFO - Chromosome '3' stat - RD parity distribution gaussian fit:  5.59 +- 3.23

```
You can try generating Manhattan plot to get some more info. 
```
cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.py -root ERS804988.pytor -100000
cnvpytor> manhattan
```

Hope it's clear to you.

**Comment by ld9866** [comment]
Dear developer:

I replaced a new individual with an average depth of 25X, and now I can complete the inspection task very smoothly.

My additional question is that I want to complete the construction of a CNV mutation map at present. How many  sequencing depth do you recommend me to use? Because it seems that very few CNV can be detected in individuals with low sequencing depth.

I detected 745 CNV in the 10Kb BIN, but only 57 CNV in the 100Kb region, what size BIN region do you recommend we use?

Best Day!

Dong

**Comment by arpanda** [comment]
Increased sequencing coverage enhances the accuracy of CNV calling. It's challenging to recommend a specific bin size, so I suggest reporting results using multiple bin sizes.

**Comment by ld9866** [comment]
The species we have done is pig genome, which is very similar to human genome, but after reading the literature, I found that the BIN Settings are very strange. 

Now I have preliminatively tested individuals and found that they differ greatly under different BIN, so I would like to ask the result of my current plan to merge 1KB, 5KB, 10KB BIN, is it reasonable?


The test sample with 45X:

22 CRR281420.100000.tsv
396 CRR281420.10000.tsv
2408 CRR281420.1000.tsv
641 CRR281420.5000.tsv

**Comment by ld9866** [comment]
I don't know if 100KB is needed and 5KB needs to be kept in the process

**Comment by ld9866** [comment]
Dear developer:
I used repeatmask and repeamoduler to generate the fasta format for the mask of the genome, but I found that new problems arose.

Could you help me?

Best!

Dong

The erro is:

2024-09-02 08:41:39,982 - cnvpytor.genome - INFO - Reading configuration file '/home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.addmask.py'.
Traceback (most recent call last):
  File "/home/lidong/miniforge3/envs/CNVpytor/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lidong/miniforge3/envs/CNVpytor/lib/python3.12/site-packages/cnvpytor/__main__.py", line 197, in main
    Genome.load_reference_genomes(args.reference_genomes_conf)
  File "/home/lidong/miniforge3/envs/CNVpytor/lib/python3.12/site-packages/cnvpytor/genome.py", line 366, in load_reference_genomes
    exec(open(filename).read(), globals())
  File "<string>", line 15
    "mask_file": "/home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/Pig_mask_file.pytor"
               ^
SyntaxError: invalid syntax


The code：
cnvpytor -root Pig_gc_file.pytor -gc Pig.fa -make_gc_file
cnvpytor -root Pig_mask_file.pytor -mask Pig.mask.fa -make_mask_file
cnvpytor -conf /home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/pig_ref_genome_conf.addmask.py -root SRR9599724.mask.pytor -rd SRR9599724.bam

The pig_ref_genome_conf.addmask.py:

import_reference_genomes = {
    "pig11": {
        "name": "pig",
        "species": "Sus scrofa",
        "chromosomes": OrderedDict(
            [("1", (274330532, "A")), ("2", (151935994, "A")), ("3", (132848913, "A")),
            ("4", (130910915, "A")), ("5", (104526007, "A")), ("6", (170843587, "A")),
            ("7", (121844099, "A")), ("8", (138966237, "A")), ("9", (139512083, "A")),
            ("10", (69359453, "A")), ("11", (79169978, "A")), ("12", (61602749, "A")),
            ("13", (208334590, "A")), ("14", (141755446, "A")), ("15", (140412725, "A")),
            ("16", (79944280, "A")), ("17", (63494081, "A")), ("18", (55982971, "A")),
             ("X", (125939595, "S")), ("Y", (43547828, "S")),
            ("MT", (16613, "M"))]),
        "gc_file":"/home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/Pig_gc_file.pytor"
        "mask_file": "/home/lidong/08.CNV/01.testsample/cnvpytor.pig.fa/Pig_mask_file.pytor"
    }
}

**Comment by arpanda** [comment]
The input mask file should be in 1000 Genomes Project [strict mask](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/working/20160622_genome_mask_GRCh38/) format. 

-Arijit

**Comment by ld9866** [comment]
I looked at the way the mask genome works, and I think we're not going to use the mask genome after all.

Another question is about the input of SNP file. I would like to ask whether the SNP VCF file is a high-quality SNP after quality control or the initial state?

**Comment by arpanda** [comment]
I am not sure what do you mean by high-quality SNP or what do you mean by quality control? Output vcf from GATK HaplotypeCaller should be fine.

**Comment by ld9866** [comment]
Since SNPS involve hard filtering to control low-quality SNPS, which vcf should I use?
