### ISSUE TITLE
Please update the genome gaps (dG) filter code

### ISSUE THREAD

**Issue by xiucz** [abyzovlab/CNVpytor#239]
Hi, 
 @arpanda 
When I use the golden data, I set `view.dG_range = [1000, np.inf]`, but a `deletion` is still being filtered out. Could you update the code to filter out only CNVs of type 'dup'? However, skipping this filter would result in a large number of false positives.

```
import cnvpytor
import numpy as np

bin_sizes = [100000]
bin_size = bin_sizes[0]

pytor = "~/test.pytor"

view = cnvpytor.Viewer([pytor],params={"bin_size": bin_size})
len(view.get_calls())
view.dG_range = [1000, np.inf]
len(view.get_calls())
```

https://github.com/abyzovlab/CNVpytor/issues/116
https://github.com/abyzovlab/CNVpytor/issues/115

Best, 
xiucz

**Comment by arpanda** [comment]
The first column has the event type. It can be easily filtered out by any external tools/scripts. For example, using excel, one can filter them out.  

-Arijit

**Comment by xiucz** [comment]
Was a genome mapping gap file used in this step? If I obtain this file, I can filter using Python code. How can I access it？
Best,
xiucz

**Comment by arpanda** [comment]
To display all results, simply remove the filtering step (i.e.,` view.dG_range = [1000, np.inf]`). You can then apply your own filtering strategy as needed.

-Arijit

**Comment by xiucz** [comment]
Oh~
I can filter the vcf file by `##INFO=<ID=pytorDG,Number=1,Type=Integer,Description="Distance to nearest gap in reference genome">`, thank you for your inspiration! At first, I found it hard to filter the pytor obj.
Best, 
xicuz

**Comment by xiucz** [comment]
The `pytorDG`   is not a good choice to filter gap events...
