### ISSUE TITLE
can you tell me how to interpretation the result 

### ISSUE THREAD

**Issue by ChenDepp** [abyzovlab/CNVpytor#241]
![企业微信截图_17261328167422](https://github.com/user-attachments/assets/4c555622-9776-4c8d-8a4d-2b3f0c637f9e)

hi @bpow 
      I merged different sample cnv and got merged cnv tsv result file. But I don't know how to understand it? So can you tell me what each column means?
waiting for you reply, hava a good day!

**Comment by bpow** [comment]
This is probably a better question for @suvakov , who looks to be the primary developer/contributor. I think I've only made one commit to this project, and have not used it in a while.

**Comment by ChenDepp** [comment]
@bpow  Thank you very much！

**Comment by ChenDepp** [comment]
@suvakov 
Hello, can you tell me? How to understand it? 
have a nice day!

**Comment by arpanda** [comment]
Hi @ChenDepp,

The merged command combines CNV calls from multiple `pytor` files. The first three columns correspond to the `event type`, `genomic coordinate`, and `event size`. From the fourth column to the second-to-last, the CNV levels for each sample are listed. Based on the data, it appears you're working with two samples. 

The last column indicates the overall call status, showing whether a CNV is called or not in that region. A value of `[0]` means the CNV is called in the first sample, `[1]` means it is called in the second sample, and `[0, 1]` means it is called in both samples.

``` tsk
duplication chr1:15038001-15340000 302000 2.57 2.47 [0]
```
In this case, the duplication is called in only one sample, even though both samples have similar copy number levels. It would be useful to inspect this discrepancy to determine why the duplication wasn't called in the second sample or whether it is a false positive CNV calling in the first sample.

I would recommend to export the results to excel which is little bit more helpful to understand and visualize few calls in both samples. Ref: https://github.com/abyzovlab/CNVpytor/blob/master/examples/merging.md . 

-Arijit
