### ISSUE TITLE
Chromosomes with RD histograms [bin sizes]:  []

### ISSUE THREAD

**Issue by Johnsonzcode** [abyzovlab/CNVpytor#246]
Hi @arpanda 
CNVpytor is a good tool, for its comprehensive function.
When I try to call CNV, there is always an error, it says as the title of this thread.

Before opening this thread, I searched all the issues in case I missed something.

The aspects I checked include chromosome names in the bam file and the genome file, the environment (I used the newest github version), the GC file (which should be fine with the size of 12Mb), and I didn't use mask file and parameter `-chrom`. 

Here is the code I used:
```shell
ref=xx.fa
cnvpytor -root mallard_gc_file.pytor -gc $ref -make_gc_file
mkdir pytor

ls bam/T23_L1.bam | parallel -N 1 -k -j 10 "cnvpytor -conf example_ref_genome_conf.py -root pytor/{/.}.pytor -rg ap1 -rd {} -v d"
ls bam/T23_L1.bam | parallel -N 1 -k -j 10 "cnvpytor -conf example_ref_genome_conf.py -root pytor/{/.}.pytor -stat 1000 10000 100000 1000000 -v d "
ls bam/T23_L1.bam | parallel -N 1 -k -j 10 "cnvpytor -root pytor/{/.}.pytor -his 1000 10000 100000 1000000 -v d"

$ cnvpytor -conf example_ref_genome_conf.py -root pytor/T23_L1.pytor -ls
2024-11-29 10:27:07,081 - cnvpytor.genome - INFO - Reading configuration file 'example_ref_genome_conf.py'.
2024-11-29 10:27:07,083 - cnvpytor.genome - INFO - Importing reference genome data: 'ap1'.

Filename 'pytor/T23_L1.pytor'
-----------------------------
File created: 2024-11-29 10:11 using CNVpytor ver 1.3.2

Chromosomes with RD signal: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ... some chrs and scaffolds

Chromosomes with SNP signal: 

Using reference genome: ap1 [ GC: yes, mask: no ]

Chromosomes with RD histograms [bin sizes]:  []

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: length of chrs and scaffolds
```

I can't figure out why, I would appreciate your reply!

**Comment by arpanda** [comment]
Hi @Johnsonzcode 
It seems your reference genome is not set to the default configuration, so you’re using the `-conf` parameter to specify it. This parameter must be included in every command to use other reference genomes. However, it is missing in your `-hist` command. i.e.,
```
ls bam/T23_L1.bam | parallel -N 1 -k -j 10 "cnvpytor -root pytor/{/.}.pytor -his 1000 10000 100000 1000000 -v d"
```
command with `-conf` parameter.
```
cnvpytor -conf example_ref_genome_conf.py -root {pytor_file} -his 1000 10000 100000 1000000 -v d
```
After this try your `ls` command:

Thanks
Arijit

**Comment by Johnsonzcode** [comment]
> Hi @Johnsonzcode It seems your reference genome is not set to the default configuration, so you’re using the `-conf` parameter to specify it. This parameter must be included in every command to use other reference genomes. However, it is missing in your `-hist` command. i.e.,
> 
> ```
> ls bam/T23_L1.bam | parallel -N 1 -k -j 10 "cnvpytor -root pytor/{/.}.pytor -his 1000 10000 100000 1000000 -v d"
> ```
> 
> command with `-conf` parameter.
> 
> ```
> cnvpytor -conf example_ref_genome_conf.py -root {pytor_file} -his 1000 10000 100000 1000000 -v d
> ```
> 
> After this try your `ls` command:
> 
> Thanks Arijit

Thank you for your quick reply, I thought `-conf` was only used when `rd` step.

Thanks
Johnson

**Comment by Johnsonzcode** [comment]
It works well, thank you!
