### ISSUE TITLE
Question: RD + AF usage

### ISSUE THREAD

**Issue by holtjma** [abyzovlab/CNVpytor#25]
Hello, I saw the pre-print and am interested in running some set with CNVpytor!  I have a question about the usage of a VCF that I couldn't clearly answer from the docs.

Predicting based off RD seems fairly straight-forward as you described here:
https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#predicting-cnv-regions

You also describe how to _import_ SNP data and calculate BAF here:
https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#calculating-baf-histograms

What isn't clear to me is if the SNP/BAF data (after importing) has any impact on the CNV calling steps of RD.  For example, if I run CNV calling with RD only and then later add the SNP data, will I get a different result if I run the RD steps again?  Or is there some additional step that combine the two?  I see steps for _viewing_ both together, but I'm primarily interested in whether the caller itself will factor in both types of information.

Suggestion: Assuming it _does_ impact it somehow, it would be useful to have a Quickstart (similar to this: https://github.com/abyzovlab/CNVpytor#call-cnvs-using-read-depth) that uses both the BAM and VCF.

**Comment by suvakov** [comment]
Sorry for delay. In the current version of CNVpytor BAF data does not impact calling. However, after calling step one can run genotype with extended output (-a option) for each call. Description of output columns is here:

https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#genotyping-genomic-regions

BAF provides additional evidence of CNV. In the case of duplication expected value for BAF level (difference from 0.5) is 1/6 and there is p-value provided. In the case of deletion loss of heterozygosity is expected and number of HETs should be zero or small comparing number of HOMs. In the case of mosaic or sub-clonal events BAF level will take any value from 0 to  1/2. In the case of mosaic or sub-clonal CNVs BAF value can take any number between 0 and 1/6 for duplication, or 0 and 1/2 for deletion depending on cell frequency/purity.

Additionally, SNP/BAF data can be used in plots (likelihood, snp, and baf panels or circular plot). See examples:
https://github.com/abyzovlab/CNVpytor#gallery

**Comment by holtjma** [comment]
Interesting, so it's primarily a secondary data source that could be used in a manual review (or perhaps some other downstream automation).  Thanks for creating this, it was very easy to set it up and run some tests!  Closing because question is answered now.
