### ISSUE TITLE
CNVpytor with a new reference genome

### ISSUE THREAD

**Issue by yeroslaviz** [abyzovlab/CNVpytor#28]
I'm working on a specific strain of S. cerevisiae, BY4741 and found this tool interesting and wanted to test it on my WGS data.

I have followed the instruction to create a conf file and made this one:

```
import_reference_genomes = {
    "BY4741": {
        "name": "BY4741",
        "species": "Saccharomyces cerevisiae",
        "chromosomes": OrderedDict(
            [("chrHIS3", (3598, "A")),("2-micron", (6318, "A")),("chr01", (230222, "A")), ("chr02", (813185, "A")), ("chr03", (305936, "A")),
            ("chr04", (1531932, "A")), ("chr05", (575777, "A")), ("chr06", (270161, "A")),
            ("chr07", (1090940, "A")), ("chr08", (562641, "A")), ("chr09", (439891, "A")),
            ("chr10", (745751, "A")), ("chr11", (666818, "A")), ("chr12", (1075778, "A")),
            ("chr13", (924428, "A")), ("chr14", (784331, "A")), ("chr15", (1091101, "A")),
            ("chr16", (948066, "A")), ("chr17", (85781, "A"))]),
        "gc_file":"/home/yeroslaviz/projects/Hartl_Dept/Gopal_WGS/GenomeII_addHIS3_hsp/CNVpytor/BY4741_gc_file.pytor"
    }
}
```

I then ran the following commands for testing the tool

```
#Initialization
cnvpytor -conf BY4741_ref_genome_conf.py -root ${sample_name}.pytor -rd $in_bam

cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -his 200 10000 
#Next step is partitioning using mean-shift method:
cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -partition 200 10000
#Finally we can call CNV regions using commands:
cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -call 200 > ${sample_name}.calls.200.tsv
cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -call 10000 > ${sample_name}.calls.10000.tsv
# Calculating BAF histograms
cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -baf 200 10000

# Visualization
## manhattan plot
cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -plot manhattan 200 10000 -o ${sample_name}.manhattan.pdf
## Circular plot:
cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -plot circular 200 1000 -o ${sample_name}.circular.pdf
```

Up to the plotting it seems to run nicely. But the manhattan plot gives me a message

```
/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/viewer.py:2273: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.yaxis.set_ticklabels([str(int(2 * t)) for t in yticks])
/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/viewer.py:2273: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.yaxis.set_ticklabels([str(int(2 * t)) for t in yticks])
```

while the circular plot results in an error

```
Traceback (most recent call last):
  File "/home/yeroslaviz/miniconda3/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/__main__.py", line 234, in main
    view.plot_command(args.plot)
  File "/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/viewer.py", line 381, in plot_command
    self.parse(command)
  File "/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/viewer.py", line 364, in parse
    self.circular()
  File "/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/viewer.py", line 2453, in circular
    dt = 2.0 * np.pi / plot_len
ZeroDivisionError: float division by zero
```

Any ideas as to how to solve this?

thanks
Assa

**Comment by suvakov** [comment]
It looks that some chromosomes are smaller than bin_size. Maybe that triggers the bug. Can you try to rerun it just for bin_size 200 or to use -chrom (or set chrom in interactive mode) to limit plot to larger chromosomes?

**Comment by yeroslaviz** [comment]
As you can see in the `conf` file above, all parts are even larger than 1000, but still even only with bin_size 200 I get the same error.

```
$ cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -plot circular 200 -chrom chr01   -o ${sample_name}.circular.pdf
2021-03-16 06:54:56,559 - cnvpytor.genome - INFO - Reading configuration file 'BY4741_conf.py'.
2021-03-16 06:54:56,560 - cnvpytor.genome - INFO - Importing reference genome data: 'BY4741'.
Traceback (most recent call last):
  File "/home/yeroslaviz/miniconda3/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/__main__.py", line 234, in main
    view.plot_command(args.plot)
  File "/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/viewer.py", line 381, in plot_command
    self.parse(command)
  File "/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/viewer.py", line 364, in parse
    self.circular()
  File "/home/yeroslaviz/miniconda3/lib/python3.6/site-packages/cnvpytor/viewer.py", line 2453, in circular
    dt = 2.0 * np.pi / plot_len
ZeroDivisionError: float division by zero
```

**Comment by yeroslaviz** [comment]
Not sure, if this has something to do with it or not, but when creating the `pytor` object I get a list os statistical parameters. 

for my smallest chromosome (basically, this is an additional transgenic seqeucnes we added into the genome before doing the WGS) I get this values

```
2021-03-16 09:21:34,074 - cnvpytor.root - INFO - Chromosome 'chrHIS3' stat - RD parity distribution gaussian fit:  200.61 +- 74.51
2021-03-16 09:21:34,074 - cnvpytor.root - INFO - Chromosome 'chrHIS3' stat - RD unique distribution gaussian fit:  209.48 +- 81.92
```

Can this be the reason for the error? But why does it happen also for a specific chromosome?

**Comment by suvakov** [comment]
You should get the same info for all chromosomes from bam file. Can you send me log form -rd step here or on email (suvakov at gmail)? Also, pytor file could help us to trace the bug if you can share it with us. Thanks.

**Comment by yeroslaviz** [comment]
Good morning and thanks for the help. 
I am attaching here both the `log` file and the `pytor` file


[RDsignal.log.zip](https://github.com/abyzovlab/CNVpytor/files/6154159/RDsignal.log.zip)
[109.pytor.zip](https://github.com/abyzovlab/CNVpytor/files/6154160/109.pytor.zip)

**Comment by suvakov** [comment]
I tested it manhattan for bin size 1000:
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/23728854/111561388-5ce52d00-8762-11eb-818b-bf9660280051.png">

Region plot also works fine:
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/23728854/111561269-30c9ac00-8762-11eb-8a0f-6b6e835814fe.png">

For circular plot you need to import SNP data and run -baf step before plotting. Not sure how frequent SNPs are in your case. In the case of human genome they occur once in roughly 1,000 bp and bins should be at least 5000 to expect multiple SNPs per bin.

There is no 200 bin size histograms (see [1000] in "Chromosomes with RD histograms [bin sizes]:"):
<img width="832" alt="image" src="https://user-images.githubusercontent.com/23728854/111561576-ab92c700-8762-11eb-9488-17b9c717f821.png">
