### ISSUE TITLE
creating rd plot for single chromosomes

### ISSUE THREAD

**Issue by yeroslaviz** [abyzovlab/CNVpytor#29]
I'm trying to plot rd plots for a single chromsome from my `pytor` data. But the plots is always empty

I have tried both via command line 

```
# all chromsomes works just fine
cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -plot rd 200 -o ${sample_name}.rd.pdf

#only chr01 gives an empty plot with no reads
cnvpytor -conf BY4741_conf.py -root ${sample_name}.pytor -plot regions chr1 200 -panels rd -o ${sample_name}.chr1.rd.pdf
```
as well as interactively

```
cnvpytor  -conf BY4741_conf.py -root ${sample_name}.pytor -view 200
set style classic
set rd_use_mask
set file_titles 109
set panels rd
set markersize 0.2
chr15
```

I have added an example of the output here.
[109.chr1.rd.regions.0000.pdf](https://github.com/abyzovlab/CNVpytor/files/6150121/109.chr1.rd.regions.0000.pdf)

**Comment by suvakov** [comment]
This is probably connected to previous issue #28. Let's solve that one first.

**Comment by suvakov** [comment]
You do not have the mask file in your reference genome config. 
Remove "set rd_use_mask" from script ant it should work.
