### ISSUE TITLE
snp plots

### ISSUE THREAD

**Issue by yeroslaviz** [abyzovlab/CNVpytor#30]
I must apologize in advance for all the issues I'm adding here. I hope it is ok. 
I was wondering if you can elaborate on how to add the `snp` information.

What `vcf` file is needed? Is it something i have used the same data set to calculate snps or is it a specific file from a specific database. 

I have ran the SNP detection pipeline from the `bcftools` (mpileup -> calls -> tabbix) and have now an indexed `vcf` file. But with this vcf file i seems to not be able to upload any SNPs onto the `pythor` object.

thanks again and hope you can answer all my questions.

Assa

**Comment by suvakov** [comment]
CNVpytor imports SNP data from VCF with following:
- PASS value in filter column (this is default, to avoid filtering use -nofilter option)
- AT (counts) and GT (genotype) tags

Minimal row should look like this:
`chr1 13801 . G A 10 PASS . GT:AD 0/1:11,12`

If you want to import only positions of SNPs you can use VCF without AD tag and specify -noAD option in command line.

For diferent AD or GT tag use -AD and -GT (see details [here](https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#import-snp-data))

**Comment by yeroslaviz** [comment]
Ok, I see. My vcf files all have just `.` in the filter column, as i have not applied any filter for them. I'll do that and report if there are any further problems. 

thanks
