### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by Swanthana-bioinfo** [abyzovlab/CNVpytor#31]
Hello 

I am trying to generate chromosome wide plots for variant file, but keep getting this error 

qt.qpa.xcb: could not connect to display 152.2.94.11:55.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Do you think I need to install anything more? I got matplotlib and python. 

Here is my command 
cnvpytor -root infile.pytor -plot baf 100000 snp -o chrm_plot.png

Thanks.

**Comment by suvakov** [comment]
Is there the same issue with other type of plots? It is probably something related to matplotlib an Qt. You can try to force agg when plotting directly into file (option -agg or --force_agg).

I recommend interactive mode or script instead of -plot option. [Here](https://github.com/abyzovlab/CNVpytor#plot-from-script) you can fins an example.

**Comment by Swanthana-bioinfo** [comment]
So, I tried using the --force_agg option which gave me the same error. I guess will try using in interactive mode, but would really love to get the graphs when used in our pipeline. Thank you.

**Comment by suvakov** [comment]
Sorry for delay. Please try to save following script into file, e.g. _script.spytor_:
```
cnvpytor -root infile.pytor -view 100000 << ENDL
set rd_use_mask
set markersize 1
set grid vertical
set output_filename test.png
manhattan
circular
```
and pipe it to cnvpytor:
```
# cnvpytor -root infile.pytor -view 100000 < script.spytor
```
There should be two output files, one for _manhattan_, and another for _circular_ plot.

In your example, plot title "... : ENDL" (blue font top left) suggests that last line is not considered as end of script but as input. Probably this is related to shell.

**Comment by Swanthana-bioinfo** [comment]
Thanks for this, I got rid of that and got some plots. Now I am trying to get something like merging example, but couldn't annotate the file, here is the error i got 

cnvpytor> set print_filename joint_calls.xlsx
    * print_filename: joint_calls.xlsx
cnvpytor> set dG_range 100000 inf
    * dG_range: [100000, inf]
cnvpytor> print joint_calls
cnvpytor> set print_filename joint_calls.xlsx
    * print_filename: joint_calls.xlsx
cnvpytor> set annotate
    * annotate: True
cnvpytor> set print_filename joint_calls.xlsx
    * print_filename: joint_calls.xlsx
cnvpytor> set plot
    * plot: True
cnvpytor> set output_filename joint.png
    * output_filename: joint.png
cnvpytor> print joint_calls
Traceback (most recent call last):
  File "/nas/longleaf/home/swan/miniconda3/envs/cnvpytor/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/nas/longleaf/home/swan/miniconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/__main__.py", line 248, in main
    view.prompt()
  File "/nas/longleaf/home/swan/miniconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/viewer.py", line 477, in prompt
    self.print_simple_joint_calls()
  File "/nas/longleaf/home/swan/miniconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/viewer.py", line 1202, in print_simple_joint_calls
    annotator = Annotator(self.reference_genome)
  File "/nas/longleaf/home/swan/miniconda3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/annotator.py", line 28, in __init__
    self.url_template = reference_genome["ensembl_api_region"]
KeyError: 'ensembl_api_region'

Is the system unable to locate the enseml api? Let me know how can I fix this, Thank you.

**Comment by suvakov** [comment]
There was a typo in key name for hg38. It is fixed. Thank you for reporting.

**Comment by Swanthana-bioinfo** [comment]
Thanks for fixing it! Do you have any documentation where it explains what those plots mean, wanted to make more sense of the lines and dots in circular plots. Thank you.

**Comment by suvakov** [comment]
All documentation we have for now you can find on GitHub pages, or by using "help" command in interactive mode. There is also our preprint available at [Biorxiv](https://www.biorxiv.org/content/10.1101/2021.01.27.428472v1) with definitions in **Materials and Methods** section. Thanks.
