### ISSUE TITLE
pN output parameter incorrect in GRCh38 chrY 

### ISSUE THREAD

**Issue by jon-coker** [abyzovlab/CNVpytor#32]
Hello, thanks again for the great tool. 

We see the following output on a GRCh38 run: 

deletion    chrY:1-2800000    2800000    0.0066    0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00    0.0035    0.1187    0    [100000 binsize]
deletion    chrY:1-2780000    2780000    0.0000    0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00    -1.0000    0.1195    0    [10000 binsize]
deletion    chrY:1-2781000    2781000    0.0000    0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00    -1.0000    0.1195    0    [1000 binsize]

In GRCh38 chrY,  we believe the first 2,781,489 bases are Ns.   To the resolution of the bin size, these CNV are calls exactly in the all-N region of chrY.  No problem (per our previous issue reported), you now give us a pN output.    We use the pN parameter to filter out these false calls.    However, in this case, the pN output is ~11.9% rather than the 100% that we should see.

**Comment by suvakov** [comment]
Hi Jon, 

This is the pseudoautosomal region - PAR1 (region that has the same sequence in X and Y chromosome). In the version of hg38 assembly that we used to extract GC/N content, PAR1 is mapped in both X and Y chromosome with gap around 12%:
<img width="1846" alt="image" src="https://user-images.githubusercontent.com/23728854/112083937-f7c07b80-8b55-11eb-9920-b52de21c4dbf.png">

However, in some versions of the reference genome, Y chromosome PAR regions are hard-masked to N. This way aligner maps reads only to the X chromosome PAR regions. You can probably see it as duplication at the beginning of X chromosome.

I suggest manual filtering chromosome Y deletion and chromosome X duplication in both PAR1 and PAR2 regions.

Thanks.

**Comment by jon-coker** [comment]
Hi Milovan:  I hadn't known about the different handling of PAR in different versions of 38.  We'll fix it on our side.  Thank you!
