### ISSUE TITLE
Refseq reference genome nomenclature

### ISSUE THREAD

**Issue by Swanthana-bioinfo** [abyzovlab/CNVpytor#33]
Hello,

I see you have GRCh38 and 37 references of ensembl and UCSC nomenclature for the chromosomes, any plans to add refseq nomenclatures too?

We use refseq nomeclature in our lab, and adding that here would be really helpful and saves 1 extra step for most of us who use refseq reference genome. Thank you.

**Comment by arpanda** [comment]
I am not sure what do you mean by refseq nomenclature. Can you please provide us example of nomenclature that you are using and how its differs from current GRCh38 reference genome.

**Comment by Swanthana-bioinfo** [comment]
I am referring to chromosomes accession, different databases have different naming patterns. Like you can see chr1 (UCSC), 1 (ensembl), refseq database has its own way of writing the chromosome names. Here is a link which might help you to look at various types 

[https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_assembly_report.txt](url)

![Screen Shot 2021-04-06 at 3 35 48 PM](https://user-images.githubusercontent.com/66682276/113768410-d337d800-96ed-11eb-9179-158a7de0357c.png)

**Comment by arpanda** [comment]
Currently, we are checking chromosome name with and without `chr'. Hence, this refseq nomenclature can't be applied directly. We need to think a general way to implement this.

Please let us know if you have any suggestions. We appreciate your feedback.

Thanks
