### ISSUE TITLE
Read depth Y axis

### ISSUE THREAD

**Issue by diogomilanesi** [abyzovlab/CNVpytor#35]
Hi,
Would like to know if there is a parameter for generating different scales in Y (Read depth) when plotting directly from command. I generate a plot with several subplots and even if I try to re-scale them individually in the opened panel after running the command, only the 0-6 RDs appear marked in each on the axis. Could not find any place with someone having the same doubt. Thanks.

**Comment by suvakov** [comment]
Our suggestion is to create a script that will be piped to cnvpytor (find an example [here](https://github.com/abyzovlab/CNVpytor#plot-from-script)). Within script you can use all parameters available in interactive mode. For y-axis range for rd plots there is parameter rd_range.

**Comment by diogomilanesi** [comment]
Ok. I closed the issue right after writing it because I found the "set rd_range 0 [num]". But when using a high number on the [num] I noticed a change from the normal read depth (RD) to a more similar value to the .bam file coverage. Ex.: when set rd_range 0 70 (because of high coverage), the displaying values in the Y scale are 0,500,1000. Is that a normal behavior?

**Comment by suvakov** [comment]
It is expected. If rd range is below 30 it will make ticks on y axis in units of copy numbers where 2 corresponds to mean autosome signal. If range is higher then 30 it will use default matplotlib ticks (units are real coverage,  i.e. number of mapped reads within bin).
