### ISSUE TITLE
CNVpytor read .root file from CNVnator

### ISSUE THREAD

**Issue by StellaXia** [abyzovlab/CNVpytor#36]
Hi, 

I'm trying to use CNVpytor to plot the read depth of a chr region called by CNVnator. 

I wonder if it is possible to use CNVpytor to directly read the .root file generated by CNVnator.
The code is as following:

(cnvpytor) [username]$ cnvpytor -root trio9_CNV/offspring.root \
> -rd JGT-29_sorted.bam \
> -chrom chr22
2021-04-24 17:58:40,119 - cnvpytor.io - ERROR - Unable to open file trio9_CNV/offspring.root!

Thank you very much and looking forward to your reply.

**Comment by StellaXia** [comment]
I tried to directly output .root file from CNVpytor but failed with the following error:

[]$ conda activate cnvpytor
(cnvpytor) []$ cnvpytor -root trio9_CNV/test.root \
> -rd JGT-29_sorted.bam \
> -chrom chrM
2021-04-28 21:23:17,504 - cnvpytor.bam - INFO - File: JGT-29_sorted.bam successfully open
2021-04-28 21:23:17,504 - cnvpytor.bam - INFO - Detected reference genome: hg38
2021-04-28 21:23:17,857 - cnvpytor.pool - INFO - Parallel processing using 8 cores
2021-04-28 21:23:18,239 - cnvpytor.root - INFO - Reading data for chromosome chrM with length 16569
2021-04-28 21:23:22,834 - cnvpytor.io - INFO - Saving chromosome RD data for chromosome 'chrM'.
2021-04-28 21:23:23,102 - cnvpytor.root - INFO - Strict mask for reference genome 'hg38' found in database.
2021-04-28 21:23:23,103 - cnvpytor.io - ERROR - Unable to open file local/miniconda3-2021.3/envs/cnvpytor/lib/python3.7/site-packages/cnvpytor/data/mask_hg38.pytor!

But autually the cnvpytor/data/mask_hg38.pytor file do exist. Grateful for any suggestion!

**Comment by suvakov** [comment]
Sorry for delay. Importing form CNVnator root file is not implemented. We are working on it.

About second issue I am nor sure what could be the reason. Looks like path is wrong. Please try:
```
$ cnvpytor -download
```
or reinstall cnvpytor directly from github.

**Comment by StellaXia** [comment]
> Sorry for delay. Importing form CNVnator root file is not implemented. We are working on it.
> 
> About second issue I am nor sure what could be the reason. Looks like path is wrong. Please try:
> 
> ```
> $ cnvpytor -download
> ```
> 
> or reinstall cnvpytor directly from github.




Thanks a lot for your reply. I tried CNVpytor -download and it did not work. I will further try to reinstall cnvpytor directly from github.

BTW, I'm wondering if there is any way to extract the normalized read depth of 22 chrs from CNVpytor or CNVnator.

Thanks again!

**Comment by suvakov** [comment]
Yes, in the case of CNVnator there are two possibilities:

1. to use c++ and root library
2. to use CNVnator/pytools (from CNVnator repository):
```
from pytools import io
iof = io.IO("file.root")                       # <- change root filename
bin_size = 10000                               # <- change bin size
chroms = iof.get_chrom_names_with_tree()
for c in chroms:
    rd = iof.get_signal(c, bin_size, "RD")[1]
    ...
``` 

CNVpytor is also python module, so you can try:
```
import cnvpytor
f=cnvpytor.IO("me11.pytor") 
for i in f.rd_chromosomes():
  rd = f.get_signal(i,10000,"RD",cnvpytor.FLAG_GC_CORR)  # <- set bin size (second argument)
  ...
```

Signal is GC corrected but not normalized. Normal level that corresponds to copy number 2 you can get by:
```
mean, stdev = io.rd_normal_level(bin_size, cnvpytor.FLAG_GC_CORR)
```
To get signal in copy number units you have to devide **rd** with **mean** and multiply by 2.

For more details how to use CNVpytor as python module check [API documentation](https://abyzovlab.github.io/CNVpytor/) and [Jupyter notebook example](examples/CNVpytor.ipynb).

**Comment by StellaXia** [comment]
Thanks a lot for your great help! I'll try and post feedback. Thanks again!
