### ISSUE TITLE
100 bp bin size

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#38]
Hi,
I am interested in genotyping around SNP sites +/- 1 kb. Which bin size should I use? Is 100 bp ok?
Thanks.

**Comment by suvakov** [comment]
I think 100 bp is good choice.

**Comment by gevro** [comment]
CNVpytor is crashing I think because of memory limits even with 128 Gb RAM when running the partition step for 100 bp. Do you have any suggestions?

**Comment by suvakov** [comment]
Strange, we tested it on 16Gb and it worked fine. I will test it again next week. Thank you for reporting.

For genotyping you do not need -partition step, -his is enough.

**Comment by gevro** [comment]
Ok. What is the partition step for then?

**Comment by gevro** [comment]
Note these are high coverage 80x - 150x whole genomes.

**Comment by suvakov** [comment]
Thanks. Partition step is needed for calling not for genotyping.

**Comment by suvakov** [comment]
@gevro In our tests with 100bp bin size 16Gb was enough. However, we found memory efficient way to do partitioning. It is 10% slower, but memory requirments are now below 1Gb for 100bp bin size. Thank you for raising this issue.

**Comment by manburst** [comment]
Dear sir @suvakov 

Is there anyway to use bin below than 100?

Thank you

**Comment by suvakov** [comment]
No. It is hard coded as native bins that cnvpytor use to store parsed RD data. Going below 100bp would mean changing the code at several places.
