### ISSUE TITLE
Bug in genotype

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#39]
Hi,
I'm getting this error:
```
# cnvpytor -root cnvpytor.rootfile -genotype 100
chr12:11396601-11436500
chr12:11396601-11436500Traceback (most recent call last):
  File "/usr/local/bin/cnvpytor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cnvpytor/__main__.py", line 211, in main
    view.genotype_prompt(list(map(binsize_type, args.genotype)), all=args.all)
  File "/usr/local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 3518, in genotype_prompt
    self.genotype(bin_sizes, line, interactive=True)
  File "/usr/local/lib/python3.6/site-packages/cnvpytor/viewer.py", line 3313, in genotype
    print("\t%f" % (2. * rc / (stat[4] * (pos2 - pos1 + 1) / bs)), end="")
IndexError: list index out of range
```

This was after:
```
        cnvpytor -root cnvpytor.rootfile -rd sample.bam -chrom chr1 chr2 chr3 ...
        cnvpytor -root cnvpytor.rootfile -his 100
        cnvpytor -root cnvpytor.rootfile -stat 100
```
I also tried without 'chr'. Same error.

**Comment by gevro** [comment]
#  cnvpytor -root cnvpytor.rootfile -ls

Filename 'cnvpytor.rootfile'
----------------------------
File created: 2021-05-17 18:00 using CNVpytor ver 1.1

Chromosomes with RD signal: chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY

Chromosomes with SNP signal: 

Using reference genome: hg38 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]:  []

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {'chr1': '248956422', 'chr2': '242193529', 'chr3': '198295559', 'chr4': '190214555', 'chr5': '181538259', 'chr6': '170805979', 'chr7': '159345973', 'chr8': '145138636', 'chr9': '138394717', 'chr10': '133797422', 'chr11': '135086622', 'chr12': '133275309', 'chr13': '114364328', 'chr14': '107043718', 'chr15': '101991189', 'chr16': '90338345', 'chr17': '83257441', 'chr18': '80373285', 'chr19': '58617616', 'chr20': '64444167', 'chr21': '46709983', 'chr22': '50818468', 'chrX': '156040895', 'chrY': '57227415'}

**Comment by suvakov** [comment]
It looks that -his step did not finished. Btw, no need for -stat step. It is now part of -his.

**Comment by gevro** [comment]
You're right, fixed it. Thank you!

**Comment by mglgc** [comment]
> You're right, fixed it. Thank you!

Hi,
Because I'm getting the same kind of error, please, could you elaborate a bit how you have fixed this kind of issue?
Thank you in advance.
