### ISSUE TITLE
plot configuration

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#4]
Hi,
Can -plot be configured with all the other parameters that are available with the -view interactive mode?

i.e.
Parameters
    * baf_colors: ['gray', 'black', 'red', 'green', 'blue']
    * bin_size: 100000
    * chrom: []
    * contrast: 20
    * dpi: 200
    * file_titles: []
    * grid: auto
    * lh_colors: ['yellow']
    * markersize: auto

etc.

**Comment by gevro** [comment]
Alternatively, is there a way to write a script that can enter the interactive mode and make the kind of plot I want?

**Comment by suvakov** [comment]
Not yet. You can pipe script to interactive mode input: 
`(echo "chr22 > file.png"; echo exit) | cnvpytor -root file.pytor -view 10000`
or from input file:
`cnvpytor -root file.pytor -view 10000 < script.cnvpytor`
However, I am not sure will this work if there are no X server (-plot should work fine in that case). We are working on better solution.

**Comment by gevro** [comment]
Yes, this works thanks.
By the way, I had to fix the matplotlib bug again so it works when there is no X server.

In viewparams.py
--> add:
import matplotlib as mpl
mpl.use('Agg')

before this line:
import matplotlib.pyplot as plt

**Comment by gevro** [comment]
Note that the bug fix above for situations where there is no XDISPLAY hasn't been addressed.

**Comment by suvakov** [comment]
The 'Agg' backend only renders images (png). If we set it as default, interactive plotting will not work. However, 'Agg' should be default if there are no X detected. The matplotlib does some auto detection before initialize backends.

**Comment by gevro** [comment]
Plotting to file still doesn't work without this fix if there is no XDISPLAY.
