### ISSUE TITLE
ImportError when perform the command

### ISSUE THREAD

**Issue by QianXiaobo** [abyzovlab/CNVpytor#40]
Hi everyone,

I got the following error message when I performed CNVpytor:
```
$ time cnvpytor -root $NAME -chrom Chr01 -rd $BAM

Traceback (most recent call last):
  File "/PATH/bin/cnvpytor", line 5, in <module>
    from cnvpytor.__main__ import main
  File "/PATH/lib/python3.9/site-packages/cnvpytor/__init__.py", line 119, in <module>
    from .bam import *
  File "/PATH/lib/python3.9/site-packages/cnvpytor/bam.py", line 7, in <module>
    import pysam
  File "/PATH/lib/python3.9/site-packages/pysam-0.16.0.1-py3.9-linux-x86_64.egg/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```
But the command `cnvpytor -h` can make sense.

I have checked this library "libssl.so.1.0.0"  and I could find it at my system path:
```
$ whereis libssl.so.1.0.0
libssl.so.1.0: /usr/lib/libssl.so.1.0.0 /usr/lib64/libssl.so.1.0.2k /usr/lib64/libssl.so.1.0.0
```

There maybe something wrong when I installed cnvpytor but I have no idea.

Best wishes,
Xb

**Comment by arpanda** [comment]
Hi Xb,
I think, you have some issue with your pysam module. Could you please check your `samtools` is working properly or not.

**Comment by QianXiaobo** [comment]
Hi Arijit,
 Thanks for your quickly reply.
I solved it by 
```
$ cp /usr/lib/libssl.so.1.0.0 /PATH/openssl-openssl-3.0.0-alpha17/local/lib
$ cp /usr/lib/libcrypto.so.1.0.0 /PATH/openssl-openssl-3.0.0-alpha17/local/lib
```
and export /PATH/openssl-openssl-3.0.0-alpha17/local/lib to my enviroment.
I think cnvpytor could find these libraries from my own enviroment and path.

Regards,
Xb

**Comment by QianXiaobo** [comment]
Hi Arijit, 

I had other issues that I got a blank result file finally. I am not sure it is OK or not to discuss under this issue.
I want to run a test and my script is as following:
```
# Read depth from bam
time cnvpytor -root $PBS_O_WORKDIR/$sample.pytor -chrom Chr01 Chr20 -rd $bam && \

# Generate histogram
time cnvpytor -root $PBS_O_WORKDIR/$sample.pytor -his 100 1000 && \

# Partition
time cnvpytor -root $PBS_O_WORKDIR/$sample.pytor -partition 100 1000 && \

# Call CNVs
time cnvpytor -root $PBS_O_WORKDIR/$sample.pytor -call 100 1000 > $PBS_O_WORKDIR/$sample.tsv
```
I got `$PBS_O_WORKDIR/$sample.pytor` and `$PBS_O_WORKDIR/$sample.tsv`, but the latter was blank one.

I really dont know what happened.

**Comment by arpanda** [comment]
Could you please check, if the calls are present or not in the pytor file by
```
cnvpytor -root $PBS_O_WORKDIR/$sample.pytor -view 1000
```
then in the interactive mode.
```
print calls
```

**Comment by QianXiaobo** [comment]
Hi Arijit, 

I configured my reference genome (not human) and then tried it as your suggestion
```
$ cnvpytor -conf /PATH/donkey_ref_genome_conf.py -root $sample.pytor -view 100
```
And in the interactive mode
```
cnvpytor> print calls
```
but got message:
```
2021-06-03 16:04:24,666 - cnvpytor.viewer - WARNING - Missing reference genome required for gview.
```
Does it mean the calls are present?

**Comment by arpanda** [comment]
The issue is with reference genome name that you provided in the `-rg` option and in the `donkey_ref_genome_conf.py`. 

Could you please share the `donkey_ref_genome_conf.py` script.  

Also, looks like you are using `CNVpytor ver 1.0`. I would recommend to use the latest `version 1.1`. That is currently available in the GitHub only. Here is the installation command.

```
pip install git+https://github.com/abyzovlab/CNVpytor.git
```

**Comment by QianXiaobo** [comment]
Arijit, thanks for your patient!

I would love to share my reference genome for donkey. And you can cite this paper [doi.org/10.1038/s41467-020-19813-7](https://doi.org/10.1038/s41467-020-19813-7)
```
import_reference_genomes = {
        "dk": {
                "name": "Donkey",
                "species": "E. africanus",
                "chromosomes": OrderedDict(
                        [("Chr01", (119294037, "A")), ("Chr02", (238844183, "A")), ("Chr03", (183772800, "A")),
                        ("Chr04", (92923151, "A")), ("Chr05", (112293617, "A")), ("Chr06", (93368415, "A")),
                        ("Chr07", (123523216, "A")), ("Chr08", (104246046, "A")), ("Chr09", (64683936, "A")),
                        ("Chr10", (90667400, "A")), ("Chr11", (85788095, "A")), ("Chr12", (106346232, "A")),
                        ("Chr13", (64922896, "A")), ("Chr14", (47677399, "A")), ("Chr15", (50236165, "A")),
                        ("Chr16", (50732815, "A")), ("Chr17", (47651721, "A")), ("Chr18", (33166870, "A")),
                        ("Chr19", (26998044, "A")), ("Chr20", (100526017, "A")), ("Chr21", (98598843, "A")),
                        ("Chr22", (38360130, "A")), ("Chr23", (47379281, "A")), ("Chr24", (46610899, "A")),
                        ("Chr25", (47158557, "A")), ("Chr26", (28693288, "A")), ("Chr27", (32167772, "A")),
                        ("Chr28", (63897334, "A")), ("Chr29", (37455388, "A")), ("Chr30", (30283642, "A")),
                        ("ChrMT", (36596, "M")), ("ChrX", (110613827, "S")), ("ChrY", (12677250, "S"))]),
                "gc_file": "/PATH/donkey_gc_file.pytor"
        }
}

```
Thanks for your answer again.

**Comment by arpanda** [comment]
I think, your reference genome setup is fine and you also ran `-his` step. To print the calls, you need to run  `-partition` and '-call' steps first. Make sure, you run those before printing the calls.

Also, update to latest cnvpytor version. We have some new features and fixes.  Could you please check, if your problem persist or not.

**Comment by QianXiaobo** [comment]
Hi Arijit, 

I am very glad to tell you that the lastest version works well! I got final calls in tsv format. Then I will try plot steps.
Thank you for help!
