### ISSUE TITLE
Discrepancy of RD value between -call and -genotype

### ISSUE THREAD

**Issue by aariani** [abyzovlab/CNVpytor#41]
Dear all,

thanks a lot for developing this tool. It's really useful. However I found a discrepancy while doing some testing.
I called CNVs in a single sample using 50Kb window (-call 50000), and saved the relative file (calls.50kb.txt). When I try to force genotype (-genotype 50000 -a) the same sample using the intervals in the file produced while calling (calls.50kb.txt) the CNV levels are always different between the 2 approach. 

Pretty much the CNV level from the call file (4th column) are always 1/2 of the CNV level called by force genotyping (2nd column). Could you explain this discrepancy? I tested it on like 10 random DEL/DUP and I always get a similar cnv level ratio.

I noticed that in the description of the call file the 4th column is defined as "CNV level - read depth normalized to 1"; while in the genotyping file is defined differently (cnv level -- mean RD normalized to mean autosomal RD level,) but I still can't understand why the 2 values are different? 

In the M&M in the paper on BiorXiv you say: "Copy number of a provided genomic region is calculated as a mean RD within the region divided by mean autosomal RD scaled by 2". Does this means that cnv_level_genotyping / 2 = cnv_level_call?

**Comment by abyzov** [comment]
Hello,
sorry for the confusion. When calling CNV the tool output RD level normalized to 1. When genotyping the tools report estimated copy number level, which is normalized to 2 for autosomes and 1 for X&Y. That is why there is discrepancy.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by aariani** [comment]
Hi Alexej,
Thanks a lot for the info. I kind of guessed that by comparing call from genotyping results (all around 2 with minimal variation around hat value). I will close the issue then.
