### ISSUE TITLE
Using CNVpytor without correction for the GC content

### ISSUE THREAD

**Issue by neuropathbasel** [abyzovlab/CNVpytor#42]
Many thanks for providing CNVpytor.
We consider CNVpytor for analyzing shallow sequencing data obtained with nanopore sequencers produced by Oxford Nanopore Technologies.
I read in your manuscript (doi: https://doi.org/10.1101/2021.01.27.428472)  that  the read depth signal is corrected by the GC content. This is of course the perfect way for any sequencing technology relying on polymerases such as those used in Illumina, PacBio or Iontorrent. Sequencing data obtained from Nanopore sequencing devices are supposed to be not affected by any GC content (e.g. https://nanoporetech.com/resource-centre/gc-bias-affects-genomic-and-metagenomic-reconstructions-underrepresenting-gc-poor). 
Accordingly I am wondering if we introduce with default settings a nanopore sequencing data another bias.
Is there a way to use CNVpytor without a GC content correction?

Looking forward to your reply.

**Comment by arpanda** [comment]
Using `--no_gc_corr` or `-nogc` option, one can run the partition and call step on the raw histogram. Here is an example of the command
```
cnvpytor -root file.pytor -nogc -partition 1000 10000 100000 
cnvpytor -root file.pytor -nogc -call 1000 10000 100000
```

Thanks
Arijit
