### ISSUE TITLE
CNVPytor not able to detect custom reference Genome

### ISSUE THREAD

**Issue by Viggy0205** [abyzovlab/CNVpytor#44]
I am trying to work with mouse data mm10 , and trying to run with the custom reference_genome config python file. But the cnvpytor in the command ` cnvpytor -conf example_ref_genome_config.py -root file.pytor -rd sample.bam` , 
detects the human genome as the default reference. Also since the organism lacked the mask file, we skipped that line in the config file.

Below is the config file for the custom ref Genome that I created : 
```
import_reference_genomes = {
    "mm9": {
        "name": "MGSCv37",
        "species": "Mus musculus",
        "chromosomes": OrderedDict(
            [("chr1", (195471971, "A")), ("chr2", (182113224, "A")), ("chr3", (160039680, "A")),
            ("chr4", (156508116, "A")), ("chr5", (151834684, "A")), ("chr6", (149736546, "A")),
            ("chr7", (145441459, "A")), ("chr8", (129401213, "A")), ("chr9", (124595110, "A")),
            ("chr10", (130694993, "A")), ("chr11", (122082543, "A")), ("chr12", (120129022, "A")),
            ("chr13", (120421639, "A")), ("chr14", (124902244, "A")), ("chr15", (104043685, "A")),
            ("chr16", (98207768, "A")), ("chr17", (94987271, "A")), ("chr18", (90702639, "A")),
            ("chr19", (61431566, "A")), ("chrX", (171031299, "S")), ("chrY", (91744698, "S")),
            ("chrM", (16299, "M"))]),
        "gc_file":"/xdisk/ritu/vignesh/MGSCv37_gc_file.pytor"
    }
}
```

**Comment by arpanda** [comment]
There is a `rg` parameter, that can be used to specify the reference genome name. 
Here is the command 
```
cnvpytor -conf example_ref_genome_config.py -root file.pytor -rd sample.bam -rg mm9
```

Thanks
Arijit

**Comment by Viggy0205** [comment]
Hi Arjit, Thanks for the response. I did try using the -rg mm9 command but it says ERROR- file.pytor is missing. if I don't use the -rg option the tool is automatically thinking that I am working with the human genome. Can you please let me know how to proceed with this?

**Comment by arpanda** [comment]
I updated the previous answer. 

Thanks
Arijit

**Comment by Viggy0205** [comment]
Hi! Actually still the same problem persists. The following is the pipeline I followed :
1) generate the gc_file.pytor using the command : 
cnvpytor -root MGSCv37_gc_file.pytor -gc mouse.fa -make_gc_file

2) after which the following example_ref_genome_config.py file was created :  

import_reference_genomes = {
    "mm9": {
        "name": "MGSCv37",
        "species": "Mus musculus",
        "chromosomes": OrderedDict(
            [("chr1", (195471971, "A")), ("chr2", (182113224, "A")), ("chr3", (160039680, "A")),
            ("chr4", (156508116, "A")), ("chr5", (151834684, "A")), ("chr6", (149736546, "A")),
            ("chr7", (145441459, "A")), ("chr8", (129401213, "A")), ("chr9", (124595110, "A")),
            ("chr10", (130694993, "A")), ("chr11", (122082543, "A")), ("chr12", (120129022, "A")),
            ("chr13", (120421639, "A")), ("chr14", (124902244, "A")), ("chr15", (104043685, "A")),
            ("chr16", (98207768, "A")), ("chr17", (94987271, "A")), ("chr18", (90702639, "A")),
            ("chr19", (61431566, "A")), ("chrX", (171031299, "S")), ("chrY", (91744698, "S")),
            ("chrM", (16299, "M"))]),
        "gc_file":"/xdisk/ritu/vignesh/MGSCv37_gc_file.pytor"
    }
}

3) then the file.pytor was tried to be created using :  

cnvpytor -conf example_ref_genome_conf.py -root file.pytor -rd /xidsk/ritu/tumor.bam

But i still get the message in the terminal as the following screenshot attached below 
<img width="1534" alt="Screen Shot 2021-07-04 at 8 56 08 PM" src="https://user-images.githubusercontent.com/32655654/124416467-ea498e80-dd0b-11eb-83da-5babca668a90.png">

So its initially says it imports mouse genome but later still continues to detect human genome and all the length printed in the terminal are human chr length. Why so ? None of the length of the chr mentioned in the example_config.py is detected by the tool. Please let me know where am I making mistake . 

PS : I have the example_config.py as well as gc_file.pytor in the working directory.  Could it be a cause of error ?

**Comment by Viggy0205** [comment]
I also have an additional question. I am trying to run the commands and I am also getting the following error : 
ValueError: The dimension of bins must be equal to the dimension of the  sample x.
I have attached the screenshot of the error. Please have a look at it and let me know. Thank you.
<img width="1550" alt="Screen Shot 2021-07-04 at 10 08 30 PM" src="https://user-images.githubusercontent.com/32655654/124420651-b9218c00-dd14-11eb-82aa-80c300546333.png">

**Comment by arpanda** [comment]
Hi,
In the rd step, it only reads the bam file and stores default size histograms. The `rg` step can be used to change the reference genome name after the rd step. 

Did you ran the below command before running the `-his` command ?
```
cnvpytor -conf example_ref_genome_config.py -root file.pytor -rg mm9
```

After that only, `-his` step will work and you can check the details using the `ls` command.  


### Update.
I did a small fix to support the `-rg` parameter in the `-rd` step. If you could reinstall using GitHub source,  the below command will work.
```
cnvpytor -conf example_ref_genome_config.py -root file.pytor -rd sample.bam -rg mm9
```

PIP installation command
```
# PIP install directly from github
pip install git+https://github.com/abyzovlab/CNVpytor.git
```

Thanks
Arijit

**Comment by Viggy0205** [comment]
Hi Arjit,

Thanks for the response! I performed the above steps but I still get the error: ValueError: The dimension of bins must be equal to the dimension of the sample x.
I have attached the screenshot of the error. Please have a look at it and let me know. Thank you.
<img width="1550" alt="Screen Shot 2021-07-04 at 10 08 30 PM" src="https://user-images.githubusercontent.com/32655654/124646270-49f98400-de49-11eb-9ed6-0a592bfc5821.png">

**Comment by arpanda** [comment]
Could you please share your bam file header or make sure the header length is same as your `example_ref_genome_config.py` file.

Here is command to check the header reference length.
```
# edit the bam_file to your bam file path
samtools view -H bam_file | grep 'SQ'`

```

**Comment by Viggy0205** [comment]
Hi Arjit, 

I ran the CNVpytor with my data and got the merged data output. However, I notice that it says deletion but there are positive values covered by green. Similarly
<img width="781" alt="Screen Shot 2021-07-23 at 2 12 44 PM" src="https://user-images.githubusercontent.com/32655654/126842341-134fc68c-87f2-43a0-9fa3-25cecf9186d9.png">
 it says duplication covered with values in red. Can you please have a look at my output and let me know what you think.

Best,
Vignesh

**Comment by arpanda** [comment]
Hi Vignesh,
I think, your custom reference genome issue is solved. I am closing this issue and created another issue with your merging and annotating calls queries as both are different queries. 

Here is the new issue link: https://github.com/abyzovlab/CNVpytor/issues/48

If your reference genome query still exists, please reopen this issue or open a new one. 

Thanks 
Arijit
