### ISSUE TITLE
empty table file

### ISSUE THREAD

**Issue by ncadez** [abyzovlab/CNVpytor#45]
I am trying to detect CNV on yeast genome. However, the -calls produce empty tsv file. These are the commands I am using:

cnvpytor -conf example_ref_genome_config.py -root Sc_root.pytor -rg Sc -rd /$/Sc.clean_sorted.bam 
cnvpytor -root Sc_root.pytor -his 1000
cnvpytor -root Sc_root.pytor -partition 1000
cnvpytor -root Sc_root.pytor -call 1000 > calls.1000.tsv

I do not get any errors in log file.

Can you please help?
Thanks, Neza

**Comment by arpanda** [comment]
Hi,
Could you please try to visualize the pytor and see the read depth pattern of the data. Also as its a new reference genome, please use the `-conf example_ref_genome_config.py` in each command. The bellow commands can be used to process the data

```
cnvpytor -conf example_ref_genome_config.py -root Sc_root.pytor  -rd /$/Sc.clean_sorted.bam
cnvpytor -conf example_ref_genome_config.py -root Sc_root.pytor  -rg Sc
cnvpytor -conf example_ref_genome_config.py -root Sc_root.pytor -his 1000
cnvpytor -conf example_ref_genome_config.py -root Sc_root.pytor -partition 1000
cnvpytor -conf example_ref_genome_config.py -root Sc_root.pytor -call 1000 > calls.1000.tsv
```

Command to visualize the data
```
cnvpytor -conf example_ref_genome_config.py -root Sc_root.pytor -view 1000

cnvpytor> manhattan
```

Thanks
Arijit

**Comment by ncadez** [comment]
Hi,

Thank you very much for your kind support! It worked – in my previous calculations  I did not include a second step in which a reference was added (-rg). Now I got a very nice plot!

I appreciate your support very much!

WIth best regards, Neža
