### ISSUE TITLE
VCF file

### ISSUE THREAD

**Issue by tea-kostic** [abyzovlab/CNVpytor#46]
Hello,

What type of VCF file should be used for CNV calling? VCF file containing germline or somatic variants, or both combined? Is there any specific variant caller that you would recommend in order to get the best results?

Thanks,
Tea

**Comment by suvakov** [comment]
Hello,

BAF analysis implemented in CNVpytor is based on germline variants (SNPs and small, single letter, indels). We do not have a recommendation for specific variant caller. For cancer samples we suggest -pileup step demonstrated in:
[using-snp-positions-from-variant-file-and-counts-from-alignment-file](https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#using-snp-positions-from-variant-file-and-counts-from-alignment-file)

Thanks,

Milovan
