### ISSUE TITLE
e-vals greater than 1

### ISSUE THREAD

**Issue by williamrowell** [abyzovlab/CNVpytor#47]
I'm applying CNVpytor to PacBio HiFi WGS data for HG002 (~15-20kb reads) aligned to the GRCh38 reference.

My workflow is:
```bash
export SAMPLE=HG002
export REF=GRCh38
cnvpytor -j 8 -root ${SAMPLE}.${REF}.nogc.pytor -rd ${SAMPLE}.${REF}.bam
cnvpytor -j 8 -root ${SAMPLE}.${REF}.nogc.pytor -his 10000 15000 20000 50000 100000
cnvpytor -j 8 -root ${SAMPLE}.${REF}.nogc.pytor -nogc -partition 10000 15000 20000 50000 100000
cnvpytor -j 8 -root ${SAMPLE}.${REF}.nogc.pytor -nogc -call 10000 15000 20000 50000 100000 > ${SAMPLE}.${REF}.cnvpytor.calls.txt
```

I can get some really nice examples by generating images, but the calls are odd and have a lot of strange e-vals.  The examples below are filtered to show calls with e-vals greater than 1.

```
deletion        chr17:24720001-25000000 280000  0.1598  9.644395e-05    6.305654e+06    9.644395e-05    6.305654e+06    0.0000  0.0000  1627200
deletion        chr17:26220001-26480000 260000  0.3456  1.219513e-02    5.198288e+05    1.219513e-02    5.198288e+05    0.0000  0.0000  147200
deletion        chr17:43240001-43280000 40000   0.0087  1.413253e+02    3.997941e-11    1.413253e+02    3.997941e-11    0.0000  0.0000  16304200
duplication     chr17:43340001-43660000 320000  0.8857  2.460111e-02    7.116755e+04    2.460111e-02    7.116755e+04    0.0000  0.0000  16404200
```

(Moved a related question to #49.)

Is it possible there's an underflow in the e-val calculations?

**Comment by zeeev** [comment]
@abyzov bump.

**Comment by suvakov** [comment]
@williamrowell My apologies for the delayed response. Thank you for reporting. Documentation was not clear. E-value (e-val columns) is defined as p-value multiplied by size of genome, divided by bin size. It represents expected number of similar events to be found just by chance due stochastic nature of RD signal and it can be larger then 1.

**Comment by zeeev** [comment]
Hello @suvakov,

Have there been any updates on this front? We'd like to writeup a guide about HiFi CNV calling using this tool, however we require VCF formatting. We could write a standalone converter, but it would be more ideal to just have a bug fix for this issue.

**Comment by suvakov** [comment]
You probably referring to issue #49 ? By default vcf output works fine, there is problem only if one use option -nogc (turning off GC correction). We are working to resolve that bug.
