### ISSUE TITLE
-rd_use_mask

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#5]
Hi,
What is the definition of this? It is not clear in the documentation?
Thanks.

**Comment by gevro** [comment]
Specifically, it isn't clear how -rd_use_mask is different from -mask_snps.

And which commands exactly need to have this set? his? call? baf? When does this need to be set exactly?

**Comment by gevro** [comment]
Also, what is the difference between:
-mask_snps
-mask_snvs

**Comment by suvakov** [comment]
-mask_snp is used to mask SNPs based on 1000GP strict mask. It will filter out SNP-s that are not in P region. During -baf step mask will be used by default.

-mask_snvs is something under development and not working/documented yet.

-rd_use_mask will use RD signal from P-region (similar to mask_snp). For now it is useful only for plotting, specially in manhattan and circular plot to reduce noise. It is possible to set/unset it in interactive mode:
`set rd_use_mask
unset rd_use_mask`

**Comment by gevro** [comment]
Thanks. Would it make sense to have it as an option also for CNV calling? Or am I missing something?

**Comment by gevro** [comment]
Also, do I need to run -mask_snps separately? Or will running -baf already take care of this?
If -baf does it already, why is there a need for a separate -mask_snps command?

**Comment by suvakov** [comment]
Using rd_use_mask for calling could be useful but not well implemented yet.

Step -baf will use mask only if it is imported previously using -mask_snps. Othervise it will use all SNPs in calculations. 

Maybe we should merge -mask_snp with -snp option. Thanks.

**Comment by gevro** [comment]
Thanks. Do you have a fix yet for the plotting issue/page size?

 

Also, would you be able to delete the dropbox file I sent you for privacy reasons?

 

Thanks,

Gilad
