### ISSUE TITLE
vcf sample name

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#53]
Hi, Does cnvpytor -snp [VCF] work with multi-sample VCF files?

Does cnvpytor know to match between the @RG SM:[sample name] tag from the BAM file and the [VCF] sample name?

**Comment by suvakov** [comment]
Yes, it works with multi-sample VCF files. Use option: -sample [sample_name] to specify sample (by default it will read first sample). Automatic match is not implemented.
