### ISSUE TITLE
Interpreting the BAF histograms

### ISSUE THREAD

**Issue by gtollefson** [abyzovlab/CNVpytor#56]
I have run CNVpytor on our data and generated BAF histograms. I have read through the CNVpytor readme docs and paper but I don't see an explaination of the colors used in the plots. I see from the source code that the three plot colors represent:

1. maf(mean MAF)
2. baf (BAF value for heterozygous SNPs)
3. likelihood function for baf (most likely value of BAF at each bin)

But it is not clear to me which color (red, grey, black) correspond with each value. Can you clarify for me?

I've attached an example plot below:

<img width="452" alt="Screen Shot 2021-08-19 at 5 33 15 PM" src="https://user-images.githubusercontent.com/32968172/130147311-4e33dfc6-5b67-46b7-888d-ffb160f2fa38.png">

Thank you,
George

**Comment by suvakov** [comment]
Thank you for reporting. We will update documentation.

If you set legend parameter (command: "set legend"), it will add legend to the plot with color labels (here I1 is difference from 1/2 of the most likely BAF value):

<img width="577" alt="image" src="https://user-images.githubusercontent.com/23728854/131755985-447d78ed-1a92-40f2-aeb2-c6cae8044cca.png">
