### ISSUE TITLE
using WES data

### ISSUE THREAD

**Issue by kxxxjo** [abyzovlab/CNVpytor#57]
Hi! First, thanks for developing this tool!

My questions are below!

1. I'm planning to analyze CNV using WES data, is it okay?

2. Are read depth data and variable data stored in the same pytor file? If not, should I get read depth data and variant data, respectively?

Thanks!

**Comment by suvakov** [comment]
Thank you.

1. You can process and plot WES data but caller will not work well due to variations in coverage. We are working on updates to cover WES data.

2. They are stored in the same file. You can import them in any order but we suggest RD first if possible.
