### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by mdozmorov** [abyzovlab/CNVpytor#59]
Following installation, CNVpytor seems to be missing the `requests` module. Steps to reproduce:
```
conda create -n cnvpytor python -y
conda activate cnvpytor
git clone https://github.com/abyzovlab/CNVpytor.git
cd CNVpytor/
python setup.py install --user # Took ~3min

cnvpytor -root ...
...
ModuleNotFoundError: No module named 'requests'
```

It can be fixed by `python -m pip install requests`. Would be good to have it fixed in the base CNVpytor install.

Thanks,
Mikhail

**Comment by suvakov** [comment]
Not sure why it is not working. There is requirement in setup.py for 'requests>=2.0'. Try install with pip:
```
conda create -n cnvpytor python -y
conda activate cnvpytor
git clone https://github.com/abyzovlab/CNVpytor.git
cd CNVpytor/
pip --user install .
```
