### ISSUE TITLE
-mask_snps: Unable to open file

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#6]
Hi,
I'm getting this error:
root@d70a413435be:/home/dnanexus# cnvpytor -root file.pytor -mask_snps
2020-03-10 03:37:08,279 - cnvpytor.io - ERROR - Unable to open file file.pytor!

**Comment by gevro** [comment]
As discussed offline, this is likely due to multiple processes trying to access the root file.

**Comment by GENEDECODERS** [comment]
how to resolve this?
