### ISSUE TITLE
Do I must run “cnvpytor -root file.pytor -mask_snps”?

### ISSUE THREAD

**Issue by m-rq** [abyzovlab/CNVpytor#65]
If I don't have the strict mask file, i.e. [GC: yes, mask: no], do I still need to run "cnvpytor -root file.pytor -mask_snps" ?
Should I omit the step of "-mask_snps", and directly run next step "cnvpytor-root file.pytor -baf 10000 100000"?

**Comment by arpanda** [comment]
You need to skip that step. As your configuration file (new reference genome) doesn't have mask file.
