### ISSUE TITLE
Exome CNV calling

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVpytor#67]
Can CNVPytor be used for exome CNV calling? At least for homozygous deletions?

**Comment by suvakov** [comment]
Mean-shift caller will not work with exome data at this moment. You can try our [new caller prototype](https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#genotyping-genomic-regions). It is working with exome data but still there are some issues we are trying to address.
