### ISSUE TITLE
duplication genotype

### ISSUE THREAD

**Issue by bluesea2018** [abyzovlab/CNVpytor#68]
Hi,
 How to infer duplication genotype : homozygous or heterozygous

**Comment by suvakov** [comment]
One way is to look BAF likelihood in the region using [advanced genotyping (-a option)](https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#genotyping-genomic-regions) for call region, e.g., for copy number 4:
BAF: 1/2 -> CN2/CN2
BAF splits: 1/4,3/4 -> CN1/CN3
loss of heterozygosity (no HETs)-> CN0/CN4

You can try our new caller that use both RD and BAF signals to make call and estimate most likely copy number model. See [example](https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#genotyping-genomic-regions).
