### ISSUE TITLE
setup.py install bug

### ISSUE THREAD

**Issue by holtjma** [abyzovlab/CNVpytor#70]
Hello,

While installing this into a Conda environment, I encountered an issue that manifest when I went to export the environment to a yaml.  Specifically, I got this error message:

```
(cnvpytor-1.2) [jholt@compile-c7-01 CNVpytor-1.2]$ mamba env export

InvalidVersionSpec: Invalid version '1.0requests>=2.0': invalid character(s)
```

I resolved it by adding a comma to the end of [this line](https://github.com/abyzovlab/CNVpytor/blob/19d1914c52f3a18995f7b941dba21779e4240ad7/setup.py#L22), and then re-installing.

**Comment by suvakov** [comment]
We updated setup.py. Thank you!
