### ISSUE TITLE
Info request: image generation and results

### ISSUE THREAD

**Issue by holtjma** [abyzovlab/CNVpytor#71]
Hello again,

I've been tinkering with some of the features in this latest release, and some of the visuals look quite promising for replacing some older tools I was using (the figures are actually my favorite part of 1.2 so far).  I had a couple questions about their usage though:

1. Does operating on command line basically require a generation of a "spytor" file for each image I want to make?  For example, I got the following working based on tutorials.  Is there some way to put all of the `set` commands within one static file and dynamically pass a locus, sample name, and output file dynamically on the command line?  I tried one of the output options but it didn't seem to work.  Alternatively, is there some basic command that will just generate a figure at a locus using some pre-determined defaults?
```
set rd_range 0 4
set style classic
set rd_use_mask
set file_titles HALB3002753
set panels rd likelihood snp
set markersize 0.2
chr1:1M-2M
save test.png
```
2. In the read depth plots, there are two lines: a grey one and a black one.  In the examples and in my test case, the grey one seems to be strictly higher than black.  Is this some sort of filtered v. unfiltered plot?

3. In the bottom two plots of [this example](https://github.com/abyzovlab/CNVpytor/blob/master/examples/region.md), the bottom one seems to be a classic B-allele raw plot.  The middle seems to show similar information (and it gets labeled as "Allele frequency" also), but is obviously somehow munged or collapsed into the heat map style.  Is there a description of what exactly generates that visual?

4. In the bottom plot of that same example, do the colors of each variant correspond to something?  Blue/light blue seems to be het and orange/yellow seems to be hom; does the intensity of the color indicate something?

Thats probably enough questions for now!

**Comment by suvakov** [comment]
1. You can use following script:
```
set rd_range 0 4
set style classic
set rd_use_mask
set file_titles HALB3002753
set panels rd likelihood snp
set markersize 0.2
set output_filename output.png
chr1:1M-2M
[locus2]
[locus3]
...
```
it will create files output.regions.0000.png, output.regions.0001.png, ... (one per locus).

It is better to use ```set output_filename output.png``` than ```save test.png```. Idea was to use ```save``` if you want to store figure already on screen from interactive mode, otherwise ```output_filename```.

If you open ```.cnvpytor/``` folder in your home folder and put file ```viewer.conf``` with settings:
```
{
  'panels': ['rd','likelihood','snp'],
  'rd_use_style': True,
}
```
those settings will be used as default. Creating ```.cnvpytor/``` will also enable CNVpytor to preserve history of commands (up arrow) between sessions.

2. Grey one is raw RD data before GC correction (see [1] for details). You can adjust colors using rd_colors parameter. Help is available by typing ```help rd_colors``` in interactive mode:
```
rd_colors
    Colors used in rd plot.
    Colors correspond to following signals: raw, gc corrected, partition, call, mosaic call

TYPE
    list of strings

DEFAULT
    ['grey', 'black', 'red', 'green', 'blue', 'cyan']

PLOTS AFFECTS
    rd, region plot with rd panel

EXAMPLE(s)
    set rd_colors red grey green black blue cyan
    unset rd_colors
    set rd_colors.1 red

SEE ALSO
    markersize, snp_colors, baf_colors, lh_colors
```
3. It is BAF likelihood function explained in [1]

4. SNP filtering and colors are explained in [1] and here (```help snp_colors`` in interactive mode):
<img width="669" alt="image" src="https://user-images.githubusercontent.com/23728854/135375691-6e84bfeb-2436-484c-b1df-b30a92805cfb.png">




[1] [CNVpytor paper on BioRxiv](https://www.biorxiv.org/content/10.1101/2021.01.27.428472v1.full)

**Comment by holtjma** [comment]
1. Okay, sounds like I'll need to make a wrapper to automate this.
2. Ah that makes sense, it might be useful to add a brief description in your example just so it's more obvious to someone reviewing the repo.
3. Same as 2.
4. Ah, I haven't been using interactive which is probably how I missed this.

Thanks for the responses!
