### ISSUE TITLE
Duplicateion Genotype

### ISSUE THREAD

**Issue by bluesea2018** [abyzovlab/CNVpytor#72]
Hi,
  How to output duplication genotype: homozygous,heterozygous ?
  Thanks

**Comment by suvakov** [comment]
One way is to look RD mean and BAF likelihood in the region of call using [advanced genotyping (-a option)](https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#genotyping-genomic-regions).

The copy number you can estimate from cnv_level output (it is normalized to 1 for autosomes, i.e. CN=2*cnv_level for autosomes, CN=cnv_level for male X and Y).

Depending on CN there are multiple possibilities:

### CN=3
There are two possibilities. Either all copies are on the same haplotype (CN0/CN3), or two copies are on one haplotype and third one on another (CN1/CN2). You can find what is he case by looking BAF level: 
- BAF: splits 1/3,2/3 (genotyping with -a option provides difference from 0.5, in this case around 0.166) -> CN1/CN2
- loss of heterozygosity (no HETs)-> CN0/CN3


### CN=4
Similarly here are three possibilities:

- BAF: 1/2 -> CN2/CN2 (homozygous)
- BAF splits: 1/4,3/4 -> CN1/CN3
- loss of heterozygosity (no HETs)-> CN0/CN4

Another way is to use our new prototype caller that automatically estimates most likely copy number model. See [example](https://github.com/abyzovlab/CNVpytor/blob/master/GettingStarted.md#genotyping-genomic-regions).

**Comment by bluesea2018** [comment]
Thanks
