### ISSUE TITLE
How to save pdf in python command ? 

### ISSUE THREAD

**Issue by xiucz** [abyzovlab/CNVpytor#77]
Hi,
After searching  all the CNVpytor github pages and the paper,  i cannot save the output pictures.
Can you help me to get the right parameters?
```
...
view.rd_use_mask = False
view.rd()
view.output_filename("AllChromsCov.pdf")
``` 
Thank you.
xiucz

**Comment by suvakov** [comment]
To set parameter, use it as instance variable:
```
...
view.output_filename="AllChromsCov.pdf"
view.rd()
```

**Comment by xiucz** [comment]
@suvakov 
Thank you !
One more question, which parameter to filter calls ?For example, 
```
set size_range 100000 inf #filter calls smaller than 100kbp
set p_N 0 0.5 # filter calls with more than 50% Ns in reference genome
```
Thank you!
xiucz

**Comment by suvakov** [comment]
Not sure if I understand your question. To set those parameters from python, you can use following code:
```
import numpy as np
...
view.size_range = [100000, np.inf]
view.p_N = [0, 0.5]
```

**Comment by xiucz** [comment]
😊  These are exactly what I want to know, thanks a lot. And I'll close the issue.

**Comment by xiucz** [comment]
@suvakov 

I am sorry to ask one question 😳， how to save the filtered view object to vcf file format from python ?

In this way, I can write all my codes with python.

Thank you.
xiucz

**Comment by suvakov** [comment]
To save filtered calls as vcf:
```
view.print_filename="output.vcf"
view.print_calls_file()
```
It assumes you have specified caller. By default it is 'rd_mean_shift'. If you are using [joint caller](https://github.com/abyzovlab/CNVpytor/blob/master/examples/JointCaller.md) specify it in 'callers' parameter:
```
view.callers=["combined_mosaic"]
```
before printing to file.

**Comment by xiucz** [comment]
@suvakov 
Thank you very much.  The more I learn, the less I know... I hope there will be a more detailed API document.
