### ISSUE TITLE
How to plot Manhattan plot in a small region ?

### ISSUE THREAD

**Issue by xiucz** [abyzovlab/CNVpytor#80]
Hi, 
I can plot manhattan plot for each chrom,
```
view.chrom = ["chr1"]
view.global_plot()
```
But how to plot regional manhattan plot , such as "chr6:10000-1000000"?

Best, 
xiucz

**Comment by suvakov** [comment]
There is no such option. You can use:
```
view.multiple_regions(["chr6:10000-1000000"])
```

**Comment by xiucz** [comment]
@suvakov 
If there is no such option to plot manhattan plot, I decide to use my own r code, how can I get data?

After reading the source code of `viewer.py`, I find the values of his_p are too big, outside of the `self.rd_manhattan_range`?

```
for c, l in chroms:
    io = self.io[0]
    mean, stdev = io.rd_normal_level(bin_size, rd_flag)
    his_p = io.get_signal(c, bin_size, "RD", rd_flag)
    pos = range(start, start + len(his_p))
    plt.plot(pos, his_p, ls='', marker='.', markersize=1)


 ```
the third column is for `pos`, and forth column is for `his_p`.

![image](https://user-images.githubusercontent.com/12706146/144027412-7ee1c927-24f3-46f4-b385-7dfdac2fad66.png)

**Comment by suvakov** [comment]
If you want copy number value divide `his_p` values with `mean` (variable assigned in third row) and multiply by 2. `his_p` is raw RD level not normalized to mean. It is ploted by adjusting y-axis ticks.

**Comment by Swanthana-bioinfo** [comment]
Hello,
I am interested to do the same, generate manhattan plots for each region of the genotype output file.  Any help how can we do that?


And also 
What plot does this code give ?   --- view.multiple_regions(["chr6:10000-1000000"])

-Thank you

**Comment by suvakov** [comment]
`view.multiple_regions(...)` is the same as typing region in interactive mode (region plot like [here](https://github.com/abyzovlab/CNVpytor/blob/master/examples/region.md)). If you want multiple regions in the same plot panel separate them by comma, e.g. `view.multiple_regions(["chr6:10000-1000000,chr7:110000-900000,chr7:100m-110m"])`. For different panels per region use space instead of comma. You can specify additional panels with `view.panels=["rd","likelihood","snp"]` if you have SNP data imported.

**Comment by xiucz** [comment]
> If you want copy number value divide `his_p` values with `mean` (variable assigned in third row) and multiply by 2. `his_p` is raw RD level not normalized to mean. It is ploted by adjusting y-axis ticks.

@suvakov 
What do you mean by **variable assigned in third row**?  , Can you show me the code here?
Thank you and I am eager to hear from you!
