### ISSUE TITLE
CNV Level interpretation

### ISSUE THREAD

**Issue by manjumoorthy95** [abyzovlab/CNVpytor#81]
I have used CNVPytor to call CNVs in exome-seq data. The CNV level column present, possess values like "1059.7". It was mentioned in one of issues that "CNV level column represents CN normalized to 1 as normal level. It means that for male X and Y chromosomes CNV level is the same as copy number, while for autosomes copy number is 2 * CNV level."

So should I interpret the copy number for above value of CNV level as 2*1059?

Also, how to get the supporting read depth for each CNV called ?

**Comment by suvakov** [comment]
Yes. Sometimes close to centromere RD has huge values. You can plot region around call region to see is it the case.

For read depth value you can get mean by:
```
cnvpytor -root normal.pytor -info 100000 > info.tsv
```
Column 'RD_GC_AUTO_100K' corresponds to copy number 2 RD level (caller output CNV level is RD value divided by this number).

**Comment by manjumoorthy95** [comment]
Ok thank you. So for deletion as well should we multiply the CNV level *2 for autosomes to determine the copy number?

**Comment by suvakov** [comment]
Yes. For example typical heterozygous deletion should be around 0.5.
