### ISSUE TITLE
plot  circular error

### ISSUE THREAD

**Issue by siqi-zZ** [abyzovlab/CNVpytor#82]
```
cnvpytor -root  a15717_FSFP202412704-1r_HCJ37DSXY_L1.realigned.pytor  a22035.realigned.pytor  a37995.realigned.pytor \
>  a19599_FSFP202412721-1r_HCHNJDSXY_L2.realigned.pytor  a27422.realigned.pytor \
>  a20167_FSFP202412701-1r_HCJ37DSXY_L1.realigned.pytor  a33699.realigned.pytor -view 100000
cnvpytor> set style bmh
    * style: bmh
cnvpytor> set rd_use_mask
    * rd_use_mask: True
cnvpytor> set file_titles a15717 a22035 a37995 a19599  a27422 a20167 a33699
    * file_titles: ['a15717', 'a22035', 'a37995', 'a19599', '', 'a27422', 'a20167', 'a33699']
cnvpytor> circular
Traceback (most recent call last):
  File "/home/*/.local/lib/python2.7/site-packages/cnvpytor/viewer.py", line 510, in prompt
    self.parse(f + [str(self.bin_size)])
  File "/home/*/.local/lib/python2.7/site-packages/cnvpytor/viewer.py", line 386, in parse
    self.circular()
  File "/home/*/.local/lib/python2.7/site-packages/cnvpytor/viewer.py", line 2619, in circular
    dt = 2.0 * np.pi / plot_len
ZeroDivisionError: float division by zero
```
Hi, manhattan I did it. but,some error in circular? Can do some help? Thank you

**Comment by suvakov** [comment]
Can you please paste here output of `cnvpytor -root file.pytor -ls` for one file.

**Comment by pwwang** [comment]
I have the exact same issue. Here is what I got:

```
❯ cnvpytor -root file.pytor -ls                                                                                                                                                            (base) ─╯

Filename 'file.pytor'
---------------------
File created: 2022-01-06 22:01 using CNVpytor ver 1.0

Chromosomes with RD signal: chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY

Chromosomes with SNP signal: 

Using reference genome: hg38 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]: chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr1, chr20, chr21, chr22, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chrX, chrY [10000]

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {'chr1': '248956422', 'chr2': '242193529', 'chr3': '198295559', 'chr4': '190214555', 'chr5': '181538259', 'chr6': '170805979', 'chr7': '159345973', 'chr8': '145138636', 'chr9': '138394717', 'chr10': '133797422', 'chr11': '135086622', 'chr12': '133275309', 'chr13': '114364328', 'chr14': '107043718', 'chr15': '101991189', 'chr16': '90338345', 'chr17': '83257441', 'chr18': '80373285', 'chr19': '58617616', 'chr20': '64444167', 'chr21': '46709983', 'chr22': '50818468', 'chrX': '156040895', 'chrY': '57227415'}
```

**Comment by pwwang** [comment]
I found that the problem is here:

https://github.com/abyzovlab/CNVpytor/blob/ad314fee21f788fe3789a9eaf3d4f78ba7360774/cnvpytor/viewer.py#L2642

and here:

https://github.com/abyzovlab/CNVpytor/blob/ad314fee21f788fe3789a9eaf3d4f78ba7360774/cnvpytor/viewer.py#L2658

When no SNP data is provided, there are probably no "SNP maf" signals.

I removed the condition in the first piece of code, and gave defaults `np.array([])` to `maf` in second, it worked. The circular plot looks like this:

![circular 10000 circular 0](https://user-images.githubusercontent.com/1188067/148497437-b5cba043-d186-4c95-958b-a7e466b49f5a.png)

**Comment by siqi-zZ** [comment]
> Can you please paste here output of `cnvpytor -root file.pytor -ls` for one file.

` cnvpytor -root   a12515.realigned.pytor -ls

Filename 'a12515.realigned.pytor'
---------------------------------
File created: 2021-11-24 17:11 using CNVpytor ver 1.1

Chromosomes with RD signal: chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22

Chromosomes with SNP signal:

Using reference genome: hg19 [ GC: yes, mask: yes ]

Chromosomes with RD histograms [bin sizes]: chr13, chr12, chr11, chr10, chr17, chr16, chr15, chr14, chr19, chr18, chr22, chr20, chr21, chr7, chr6, chr5, chr4, chr3, chr2, chr1, chr9, chr8 [1000, 10000, 100000]

Chromosomes with SNP histograms [bin sizes]:  []

Chromosome lengths: {'chr13': '115169878', 'chr12': '133851895', 'chr11': '135006516', 'chr10': '135534747', 'chr17': '81195210', 'chr16': '90354753', 'chr15': '102531392', 'chr14': '107349540', 'chr19': '59128983', 'chr18': '78077248', 'chr22': '51304566', 'chr20': '63025520', 'chr21': '48129895', 'chr7': '159138663', 'chr6': '171115067', 'chr5': '180915260', 'chr4': '191154276', 'chr3': '198022430', 'chr2': '243199373', 'chr1': '249250621', 'chr9': '141213431', 'chr8': '146364022'}`

This is a file -ls

**Comment by siqi-zZ** [comment]
> I found that the problem is here:
> 
> https://github.com/abyzovlab/CNVpytor/blob/ad314fee21f788fe3789a9eaf3d4f78ba7360774/cnvpytor/viewer.py#L2642
> 
> and here:
> 
> https://github.com/abyzovlab/CNVpytor/blob/ad314fee21f788fe3789a9eaf3d4f78ba7360774/cnvpytor/viewer.py#L2658
> 
> When no SNP data is provided, there are probably no "SNP maf" signals.
> 
> I removed the condition in the first piece of code, and gave defaults `np.array([])` to `maf` in second, it worked. The circular plot looks like this:
> 
> ![circular 10000 circular 0](https://user-images.githubusercontent.com/1188067/148497437-b5cba043-d186-4c95-958b-a7e466b49f5a.png)

Hello, Could you share how to "gave defaults np.array([]) to maf " in code detail? thanks a lot~

**Comment by siqi-zZ** [comment]
> I found that the problem is here:
> 
> https://github.com/abyzovlab/CNVpytor/blob/ad314fee21f788fe3789a9eaf3d4f78ba7360774/cnvpytor/viewer.py#L2642
> 
> and here:
> 
> https://github.com/abyzovlab/CNVpytor/blob/ad314fee21f788fe3789a9eaf3d4f78ba7360774/cnvpytor/viewer.py#L2658
> 
> When no SNP data is provided, there are probably no "SNP maf" signals.
> 
> I removed the condition in the first piece of code, and gave defaults `np.array([])` to `maf` in second, it worked. The circular plot looks like this:
> 
> ![circular 10000 circular 0](https://user-images.githubusercontent.com/1188067/148497437-b5cba043-d186-4c95-958b-a7e466b49f5a.png)

Hello, Could you share how to "gave defaults np.array([]) to maf " in code detail? thanks a lot~

**Comment by suvakov** [comment]
Apologies for the delayed response. For circular plot you have to import SNP data.

Please follow [example](https://github.com/abyzovlab/CNVpytor/blob/master/examples/circular.md). VCF file should contain SNPs with AD, GT tags.
