### ISSUE TITLE
Wired manhattan plot

### ISSUE THREAD

**Issue by AIBio** [abyzovlab/CNVpytor#84]
Hi,

I have read the published paper in BioRxiv (CNVpytor: a tool for CNV/CNA detection and analysis from read depth and allele imbalance in whole genome sequencing). It is an excellent work!!!

CNVpytor is an useful tools to help me address some questions that the reviewers asked in my paper.

I want to use low sequencing depth WGS data from the abnormal embryos (around 20M PE reads) to check for aneuploidies.

But I got a wired manhattan plot (below).

![图片](https://user-images.githubusercontent.com/37030861/144458948-5b315de2-6b49-414f-baa0-af707668bcd8.png)

Could you give me some suggestions? or the running code to get the manhattan plot (below) in published paper?

![图片](https://user-images.githubusercontent.com/37030861/144452670-290a62d0-c205-4c28-9d07-1de26badd468.png)

The main steps to process WGS data are as follows:
1. fastqc to check the data quality
2. trimgalore to trim adapters and filter read pairs with low quality;
3. fastqc to check again;
4. mapping to genome with bwa (bwa mem -K 100000000 -a -p -v 3 -t 20 -Y -R '@RG\tID:group\tLB:library\tPL:illumina\tPU:unit\tSM:sample');
5. post-processing bam files, including: picard SortSam + picard MarkDuplicates;
6. use the post-processed bam file to run example code (https://github.com/abyzovlab/CNVpytor/blob/master/examples/manhattan.md);

`bam=./results/picard/markdup/R21130305-YX-DNA-DNA-1C2_combined_R1_val_1_R21130305-YX-DNA-DNA-1C2_combined_R2_val_2_psort_markdup.bam`
`~/.local/bin/cnvpytor -root 1C2.pytor -chrom $(seq -f "chr%g" 1 22) chrX chrY -rd $bam`
`~/.local/bin/cnvpytor -root 1C2.pytor -his 100000`
`~/.local/bin/cnvpytor -root 1C2.pytor -view 100000`

Finnally, I got the wired manhattan plot (above). I tried to remove duplicates to run again. But it didn't work (below).

![图片](https://user-images.githubusercontent.com/37030861/144457692-540c22ff-3038-44b1-83d2-f54405fcfafc.png)

Some warnning messages were reported by CNVpytor when running the example code (https://github.com/abyzovlab/CNVpytor/blob/master/examples/manhattan.md);

> 2021-12-02 23:45:10,437 - cnvpytor.utils - WARNING - Problem with fit: Runtime Error. Using mean and std instead fitting parameters!

> 2021-12-02 23:45:20,686 - cnvpytor.utils - WARNING - Problem with fit: negative mean. Using mean and std instead fitting parameters!

> cnvpytor> manhattan
> /home/yhw/.local/lib/python3.7/site-packages/CNVpytor-1.2-py3.7.egg/cnvpytor/viewer.py:2465: UserWarning: FixedFormatter should only be used together with FixedLocator

**Comment by suvakov** [comment]
Apologies for the delayed response. It looks that sample quality is not so good. Even for shallow coverage 100kbp bins should work fine. You can try with larger bins (e.g. 1M).
