### ISSUE TITLE
TypeError in plot 

### ISSUE THREAD

**Issue by Yali1989** [abyzovlab/CNVpytor#85]
`cnvpytor -root NT053-04_BDSW192000583-1a.pytor -view 100000`
`cnvpytor> set style bmh`
`cnvpytor> set rd_use_mask`
`cnvpytor> manhattan`
`Traceback (most recent call last):`
 ` File "/nfs_fs/nfs0/wangyali/.local/lib/python3.9/site-packages/cnvpytor/viewer.py", line 508, in prompt`
   ` self.parse(f + [str(self.bin_size)])`
  `File "/nfs_fs/nfs0/wangyali/.local/lib/python3.9/site-packages/cnvpytor/viewer.py", line 377, in parse`
   ` self.global_plot()`
 ` File "/nfs_fs/nfs0/wangyali/.local/lib/python3.9/site-packages/cnvpytor/viewer.py", line 2415, in global_plot`
   ` for c, (l, t) in self.reference_genome["chromosomes"].items():`
`TypeError: 'NoneType' object is not subscriptable`

Hi, I would like use CNVpytor to detect CNVs in a plant whole genome sequence.  After I finished CNVs calling, I used manhattan and circular plot graph, but the error above accurred.  My chromosome names are Hic_asm_0, Hic_asm_1, Hic_asm_2, Hic_asm_3, Hic_asm_4, Hic_asm_5, Hic_asm_6, Hic_asm_7, Hic_asm_8, Hic_asm_9, Hic_asm_10, Hic_asm_11.  Can you help me?

**Comment by suvakov** [comment]
Please try to configure reference genome you are using. Here is an [example](https://github.com/abyzovlab/CNVpytor/blob/master/examples/AddReferenceGenome.md).

There is new feature (not documented yet). To create template for config file from reference fasta, just run:
```
cnvpytor -fasta2rg file.fasta.gz
```
