### ISSUE TITLE
Strange CNV level values

### ISSUE THREAD

**Issue by mdozmorov** [abyzovlab/CNVpytor#88]
Following the [Annotating calls and merging over multiple samples](https://github.com/abyzovlab/CNVpytor/blob/master/examples/merging.md) tutorial, I created a joint file at 100kb resolution. CNV level values for one region seem to be off-limit:
![image](https://user-images.githubusercontent.com/864945/148549683-53682cd7-504d-43a2-945a-11795aff79c0.png)
Exploring the coverage bigWig files didn't show such abnormal coverage.
![image](https://user-images.githubusercontent.com/864945/148550217-b3e9e498-d7fa-47b1-b118-646ef27ad282.png)
Exploring the `tsv` files outputted with `cnvpytor -root ${FILEOUT1} -call 100000 > ${FILEOUT11}` didn't show this region in the first file, where it shows abnormal CNV level. In the second file, the region looks reasonable (although I still don't understand why CNV level in the TSV is 2.4 and in the joint Excel file is 5).
![image](https://user-images.githubusercontent.com/864945/148550934-291a7d22-c7f8-4e55-8d0a-05d77ebe25f3.png)
The issue appears at 100kb resolution and doesn't at 1kb and 10kb resolutions. What may be going on? 
Thanks,
Mikhail

**Comment by suvakov** [comment]
Apologies for the delayed response. The level 2.4331 means that RD here is 2.4 times normal diploid level. It corresponds to CN 5 (in Excel it is rounded to nearest integer but you can adjust to more digits). Level in the first file is strange. Can you share pytor file with me? Thanks

**Comment by mdozmorov** [comment]
Thanks, Milovan - I shared the file with your .rs e-mail. Please, request permissions if needed.

**Comment by suvakov** [comment]
Hi Mikhail, 

We fixed the bug. It was related to GC correction for bins that are outliers in GC content. As result of this bug one bin (165,100,000) had overestimated RD level (~1e9) and genotyped RD level was artificially high. 

You can now update cnvpytor and rerun steps including and after "-his" step for 100kbp bin size. 

Thank you for reporting this case and sharing pytor file. It was crucial to reproduce the bug.

Off topic: I see that mean-shift caller failed here to resolve all chr3 events correctly. For cancer samples I recommend you to try our new [joint caller](https://github.com/abyzovlab/CNVpytor/blob/master/examples/JointCaller.md).

**Comment by mdozmorov** [comment]
Thanks, Milovan. Closing as resolved, and I'll try the joint caller.
