### ISSUE TITLE
Download Path

### ISSUE THREAD

**Issue by christopher-schroeder** [abyzovlab/CNVpytor#9]
It would be really beneficial for our projects, if we could set the download path for the reference GC content files by an argument.

**Comment by suvakov** [comment]
Are you referring to download after pip installation:
> cnvpytor -download
This would download GC and mask data to the python package resource path. We did it this way because of pypi repository limit. If you clone and install cnvpytor from GitHub resource files will be automatically copied to package data path. Why do you need different location?

**Comment by christopher-schroeder** [comment]
Yes, I'm referring to cnvpytor -download. Excatly, it downloads the data to the python package resource path and the downloading itself is perfectly fine. But it would be great, if you can set the download path to a different location via an argument. For example
`cvnpytor -download -dbpath ./foo`
and of course for every following command e.g.
`cnvpytor -root file.pytor -his 10000 100000`

The reason behind this maybe rather complicate: We don't have a single global Python installation, but many different encapsulated environments with specific fixed versions of pythons

**Comment by christopher-schroeder** [comment]
Yes, I'm referring to cnvpytor -download. Excatly, it downloads the data to the python package resource path and the downloading itself is perfectly fine. But it would be great, if you can set the download path to a different location via an argument. For example
`cvnpytor -download -dbpath ./foo`
and of course for every following command e.g.
`cnvpytor -root file.pytor -his 10000 100000`

The reason behind this may be rather complicate: We don't have a single global Python installation, but many different encapsulated environments with specific fixed versions of for example Python.
Since the data is stored within the package path, we have to perform -download for each of them. So this data may be stored multiple times for a single workflow.
Second our pipelines are completely automatic. So normally for reference files it automatically checks its existence and downloads it be itself if they are missing. In that case we can easily transfer pipelines between projects servers, without any data files. One solution might be, that we check the existence before for every cnvpytor -rd command, but they might be executed in parallel for different samples, and we dont know what happens if -download is then executed in parallel multiple times.
Furthermore we currently introduce a cache system, so that references are shared not only between different steps of the pipelines, but also between different pipelines. In that case we don't have to download reference genomes multiple times and can still reproduce every step years after.
So it would be very beneficial if the gc-reference and mask-reference could be stored in a destination of our choice, like every other reference - for example the human genome reference sequence.

**Comment by suvakov** [comment]
Sorry for delay. You closed issue and I forgot to answer. There is one way to do that with option 
`cnvpytor -conf file.conf ...`
This option is developed for new reference genomes but it will work here. It reads configuration file and overwrites reference genome info. Configuration file.conf should contain reference genome data and link to files:

```
import_reference_genomes = {
       "hg19": {
            "name": "GRCh37",
            "species": "human",
            "chromosomes": OrderedDict(
                [("chr1", (249250621, "A")), ("chr2", (243199373, "A")), ("chr3", (198022430, "A")),
                 ("chr4", (191154276, "A")), ("chr5", (180915260, "A")), ("chr6", (171115067, "A")),
                 ("chr7", (159138663, "A")), ("chr8", (146364022, "A")), ("chr9", (141213431, "A")),
                 ("chr10", (135534747, "A")), ("chr11", (135006516, "A")), ("chr12", (133851895, "A")),
                 ("chr13", (115169878, "A")), ("chr14", (107349540, "A")), ("chr15", (102531392, "A")),
                 ("chr16", (90354753, "A")), ("chr17", (81195210, "A")), ("chr18", (78077248, "A")),
                 ("chr19", (59128983, "A")), ("chr20", (63025520, "A")), ("chr21", (48129895, "A")),
                 ("chr22", (51304566, "A")), ("chrX", (155270560, "S")), ("chrY", (59373566, "S")),
                 ("chrM", (16571, "M"))]),
            "gc_file": "YOUR_PATH/gc_hg19.pytor",
            "mask_file": "YOUR_PATH/mask_hg19.pytor"
        },
        "hg38": {
            "name": "GRCh38",
            "species": "human",
            "chromosomes": OrderedDict(
                [("chr1", (248956422, "A")), ("chr2", (242193529, "A")), ("chr3", (198295559, "A")),
                 ("chr4", (190214555, "A")), ("chr5", (181538259, "A")), ("chr6", (170805979, "A")),
                 ("chr7", (159345973, "A")), ("chr8", (145138636, "A")), ("chr9", (138394717, "A")),
                 ("chr10", (133797422, "A")), ("chr11", (135086622, "A")), ("chr12", (133275309, "A")),
                 ("chr13", (114364328, "A")), ("chr14", (107043718, "A")), ("chr15", (101991189, "A")),
                 ("chr16", (90338345, "A")), ("chr17", (83257441, "A")), ("chr18", (80373285, "A")),
                 ("chr19", (58617616, "A")), ("chr20", (64444167, "A")), ("chr21", (46709983, "A")),
                 ("chr22", (50818468, "A")), ("chrX", (156040895, "S")), ("chrY", (57227415, "S")),
                 ("chrM", (16569, "M"))]),
            "gc_file": "YOUR_PATH/gc_hg38.pytor",
            "mask_file": "YOUR_PATH/mask_hg38.pytor"
        }
}
```

Mask and GC files you can manually download from https://github.com/abyzovlab/CNVpytor/tree/master/cnvpytor/data to YOUR_PATH/. Furthermore, if you do not want to use `cnvpytor -conf file.conf` each time you can set up a bash alias.
