### ISSUE TITLE
How to automate export VCF file output for multiple samples 

### ISSUE THREAD

**Issue by KrithikaSubramanian** [abyzovlab/CNVpytor#98]
Hi,

I have more than 100 Human samples .pytor files which are completed until **call CNV region** step. Using the below steps I have generated a VCF file for one sample, it worked well. I tried to automate these steps in the bash/python script, but it didn't work.  Could you please help me with how can I automate the below steps for multiple samples?

```
cnvpytor -root input.pytor -view 100000
set Q0_range -1 0.5
set p_range 0 0.0001
set p_N 0 0.5
set print_filename output.vcf
set annotate
print calls
quit
```

Thanks in advance
Krithika S

**Comment by arpanda** [comment]
Hi Krithika,
Please have a look at the [`Plot from script`](https://github.com/abyzovlab/CNVpytor#plot-from-script) section. We have showed some examples to do it using terminal. 

Alternatively, using python one can automate the above script. Here is an example. 

```
import cnvpytor
from pathlib import Path


# the "pytor_files" is the name of the directory. 
pytor_files = Path("pytor_files").glob("*.pytor")
for pytor_file in pytor_files:
    print(pytor_file)
    file_list = [str(pytor_file)]
    app = cnvpytor.Viewer(file_list, params={} )
    app.bin_size = 100000
    app.Q0_range=[-1, 0.5]
    app.p_range=[0, 0.0001]
    app.p_N=[0, 0.5]
    app.print_filename="{}.vcf".format(pytor_file.stem)
    app.annotate=True
    app.print_calls_file()
```

Thanks
Arijit

**Comment by KrithikaSubramanian** [comment]
Thank you. I tried, but it shows the below error.

**MoTTY X11 proxy: Unsupported authorisation protocol
test_pytor/003RS_F1.pytor
Traceback (most recent call last):
  File "auto_python.py", line 17, in <module>
    app.print_calls_file()
AttributeError: 'Viewer' object has no attribute 'print_calls_file'**

**Comment by arpanda** [comment]
Could you please share your installed CNVpytor version. Here is the command to check the version.
```
cnvpytor --version
```
If its not latest (CNVpytor 1.2), please use the below code to install.
```
pip install git+https://github.com/abyzovlab/CNVpytor.git
```

**Comment by lgmgeo** [comment]
If it can be useful for users, here is my csh script (script.pytor.csh):
![image](https://user-images.githubusercontent.com/49909073/166928599-b148f738-49cf-4545-a9a3-013fe2e685d9.png)

Easy to run for multiple samples and several bin sizes:
./script.pytor.csh

Best,
Véronique

**Comment by arpanda** [comment]
Hi Véronique,
Thanks a lot. 
Is it possible for you to put the code it as text instead of image ? As People like to copy paste a lot then rewrite. 

-Arijit

**Comment by lgmgeo** [comment]
Sure:
```
#!/bin/csh

# CNVpytor: Exporting CNV calls as VCFs
#######################################

# WARNING: Do not indent the code between "<<ENDL" and "ENDL"
foreach sample (sample1 sample2)
        foreach binsize (1000 10000 100000)
                echo "...creation of ${sample}_cnvpythor_$binsize.vcf and ${sample}_cnvpythor_$binsize.filtered.vcf"
                cnvpytor -root $sample.pytor -view $binsize <<ENDL
set print_filename ${sample}_cnvpythor_$binsize.vcf
print calls
set Q0_range -1 0.5
set p_range 0 0.0001
set p_N 0 0.5
set print_filename ${sample}_cnvpythor_$binsize.filtered.vcf
print calls
ENDL
        end
end
```
